### ISSUE TITLE
confirm dialog blurry on demo page

### ISSUE THREAD

**Issue by MilosStanic** [justindujardin/ng2-material#10]
As the subject says... the confirm dialog on demo page is blurry. Probably some css thing.

**Comment by justindujardin** [comment]
Thanks for reporting, been meaning to look into that.  This should be fixed in `0.1.5` and on the example site. Please re-open if you still see the issue.

**Comment by MilosStanic** [comment]
Well, now both confirm and alert dialogs are blurry :)

**Comment by justindujardin** [comment]
Okay, I'll look at it again.

**Comment by DennisRoam** [comment]
@MilosStanic What OS/Browser? I'm on OSX with Chrome and FF and not seeing that.. Maybe post a screenshot?

**Comment by MilosStanic** [comment]
@DennisRoam Ubuntu 14.04, Chrome. But now I tested it in FF and it's not blurry in it. 
here's screenshot from Chrome: 
![screenshot from 2016-01-27 22 58 59](https://cloud.githubusercontent.com/assets/3983854/12629872/fb26dd64-c549-11e5-8071-1caef163c8c0.png)

**Comment by ollwenjones** [comment]
I didn't notice it before, but I see it in Chrome on windows now also (Version 48.0.2564.97)

**Comment by ollwenjones** [comment]
Has to do with the centering via `translate3d`
```css
transform: translate3d(-50%, -50%, 0) scale(1);
```
Which seems like it's only there to center it... Doesn't seem like we _need_ to use translate3d to center a flexed object. We primarily need the 'scale' part for the way it zooms in, right?

**Comment by fax-monkey** [comment]
Translate3d seems to be used to center the dialog without the need for javascript or fixed widths. It's quite elegant imho.

The blurring does have to do with translate3d, but can easily be fixed by adding:
 
    -webkit-filter: blur(0px);

to the `.md-dialog.md-active` css.

All the browser specific css to set filter:

    filter: none; 
    -webkit-filter: blur(0px); 
    -moz-filter: blur(0px); 
    -ms-filter: blur(0px);
    filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius='0');

Source: [this stackoverflow post](http://stackoverflow.com/questions/27060690/webkit-transform-scale-blurry-images).

**Comment by ollwenjones** [comment]
sweet :+1:

**Comment by justindujardin** [comment]
@fax-monkey thanks for tracking this down!
