### ISSUE TITLE
ng-invalid on inputs using ngcontrol

### ISSUE THREAD

**Issue by fxck** [justindujardin/ng2-material#100]
taken from https://justindujardin.github.io/ng2-material/#/components/input

![image](https://cloud.githubusercontent.com/assets/1303561/13573025/bb03d072-e47d-11e5-8442-22c073611c1b.png)

I've tried using ngModel as well, which results in valid inputs, but no value shown

@justindujardin ?

**Comment by ollwenjones** [comment]
@fxck I am able to use [(value)]="model.prop" just fine in my work. Any possibility you could post a gist/plunkr to rule out other data-binding / formbuilder issues?

**Comment by fxck** [comment]
Yes, but are you using it along `FormBuilder` / `ngControl`, are you getting your values from `form.value` and checking whether all is valid with `form.valid`? Because it clearly doesn't work in the official example, those inputs might be visibly filled in, but form builder knows nothing about them. 

I've managed to get it working along `[ngModel]` by modifying input directive like this 

```
export class InputCmp {
  _value: string;

  @Input('ngModel')
  set value(value: string) {
    this._value = value;
    ObservableWrapper.callEmit(this.mdChange, this.value);
  }

  get value(): string {
    return !isBlank(this._value) ? this._value : '';
  }

  @Input()
  public placeholder: string;

  @Output('valueChange')
  public mdChange: EventEmitter<any> = new EventEmitter();

  @Output()
  public mdFocusChange: EventEmitter<any> = new EventEmitter(false);

  setHasFocus(hasFocus: boolean) {
    ObservableWrapper.callEmit(this.mdFocusChange, hasFocus);
  }

}
```

but I can't say it's 100% working, sometimes it randomly ignores one of the inputs for no good reason.

**Comment by ollwenjones** [comment]
I'm using the `FormBuilder / ngControl`, yes.  One required validator on each field, and the `formName.valid` property to disable a button until the fields are filled in.  However I am not getting values from `form.value` I just have another POJO model on the component class. I wonder if / why that would make a difference?

**Comment by ollwenjones** [comment]
fwiw, binding `ngModel` as an `@Input()` feels kind of dirty somehow...

**Comment by awerlang** [comment]
Form controls should implement `ControlValueAccessor`, otherwise they won't support forms. It *may* work sometimes when you just have an `ngControl` on a regular `input`, but a custom control needs more than that.

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
