### ISSUE TITLE
I am facing issue Property 'toggle' does not exist on type 'MdBackdrop'.

### ISSUE THREAD

**Issue by ahmedanees** [justindujardin/ng2-material#101]
D:/angular2-seed-ng2-material/node_modules/ng2-material/components/sidenav/sidenav.ts(152,24): error TS2339: Property 'toggle' does not exist on type 'MdBackdrop'.

D:/angular2-seed-ng2-material/node_modules/ng2-material/components/sidenav/sidenav.ts(152,24): error TS2339: Property 'toggle' does not exist on type 'MdBackdrop'.
D:/angular2-seed-ng2-material/node_modules/ng2-material/components/sidenav/sidenav.ts(154,15): error TS2339: Property 'toggle' does not exist on type 'MdBackdrop'.
[21:04:00] TypeScript: 2 semantic errors

===============================================================

I copy https://justindujardin.github.io/ng2-material/#/components/sidenav and place 
D:\angular2-seed-ng2-material\node_modules\ng2-material\components\sidenav

[sidenav -.ts.txt](https://github.com/justindujardin/ng2-material/files/161613/sidenav.-.ts.txt)
[sidenav_service.ts.txt](https://github.com/justindujardin/ng2-material/files/161614/sidenav_service.ts.txt)

**Code that call **

import {Component} from 'angular2/core';

//import {PeopleList} from '../../services/people_list';
//import {MATERIAL_DIRECTIVES} from 'ng2-material/all';
import {MATERIAL_DIRECTIVES } from 'ng2-material/all';
import {Media} from 'ng2-material/core/util/media';
import {SidenavService} from 'ng2-material/components/sidenav/sidenav_service';

@Component({
  selector: 'about',
  providers: [SidenavService],
  templateUrl: './components/about/about.html',
  directives: [MATERIAL_DIRECTIVES]
})
export class AboutCmp {
  public nameModel: string = '';

  constructor(public sidenav: SidenavService) {
  }
  hasMedia(breakSize: string): boolean {
    return Media.hasMedia(breakSize);
  }
  open(name: string) {
    this.sidenav.show(name);
  }
  close(name: string) {
    this.sidenav.hide(name);
  }
}

**Comment by justindujardin** [comment]
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.
