### ISSUE TITLE
md-input strange behaviour in chrome 48&49

### ISSUE THREAD

**Issue by Nefarion** [justindujardin/ng2-material#103]
a md-input will jump to the back of the text with the carret when you change it
happens in Chrome 48, 49, 
does not happen in Microsoft Edge

http://plnkr.co/edit/TCDlwJ5L8YvSsIj2wUvx?p=preview

try for yourself, edit the value of the textbox and the cursor will jump

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
