### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by sysmat** [justindujardin/ng2-material#108]
Hi!

I'm trying simple application, but it failed to load, when I'm using MATERIAL_DIRECTIVES, but if I omit this, then application is running but not as expected

Code:
-------
`
from import {MdPatternValidator, MdMinValueValidator, MdNumberRequiredValidator, MdMaxValueValidator, MATERIAL_DIRECTIVES} from 'ng2-material/all';
...

directives: [ MATERIAL_DIRECTIVES]
`
package.json:
-----------------
`
"dependencies": {
        "angular2": "2.0.0-beta.9",
        "ng2-material": "0.2.11",
        "angular2-rest": "0.1.0",
        "ng2-toastr": "0.1.6",
        "bootstrap": "3.3.6",
        "es6-promise": "3.0.2",
        "es6-shim": "^0.33.3",
        "reflect-metadata": "0.1.2",
        "rxjs": "5.0.0-beta.2",
        "systemjs": "0.19.23",
        "zone.js": "0.5.15"
    }
`

Error:
--------
Error: Unexpected token <(…)Zone.run @ angular2-polyfills.js:1243

Any idea?

Regards, Tomaž

**Comment by ggitau** [comment]
Getting the same error. Error goes away when i remove the import from ng2-material/all

**Comment by ggitau** [comment]
the all script seems to get downloaded without the .js extension which essentially downloads index.html as a JavaScript file leading to the error.

**Comment by sysmat** [comment]
Then from where you add import in *.ts files?

**Comment by geelus** [comment]
I'm having the exact same issue. I started a brand new angular2 project using the exact instructions on the angular.io website. Then added the ng2_material. I'm getting unexpected token...

**Comment by sysmat** [comment]
The problem went out whit this dependency:

"dependencies": {
        "angular2": "2.0.0-beta.11",
        "ng2-material": "0.2.12",       
        "angular2-rest": "0.1.0",
        "ng2-toastr": "0.1.6",
        "bootstrap": "3.3.6",
        "es6-promise": "3.0.2",
        "es6-shim": "^0.35.0",
        "reflect-metadata": "0.1.2",
        "rxjs": "5.0.0-beta.2",
        "systemjs": "0.19.23",
        "zone.js": "0.6.4"
    }

Regards, Tomaž

**Comment by sysmat** [comment]
With "angular2": "2.0.0-beta.12" and directives: [ MATERIAL_DIRECTIVES] error re appears

Regards, Tomaž

**Comment by robertodecurnex** [comment]
Hi @sysmat 

I have been facing some problems with how the NPM package is packaged, you should be able to make it work by config

```
      System.config({
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          'ng2-material': {
            format: 'register',
            defaultExtension: 'js'
          }
        },
        map: {
          'ng2-material': 'node_modules/ng2-material'
        }
      });
```

Now... Second problem, the `all.js` that comes there (`node_modules/ng2-material') is ES6 compiled, you mayhave troubles using that one directly. You can either go the webpack way or compile your own ES5 version from the `node_modules/ng2-material/source/all.ts` one.

**Comment by geelus** [comment]
Hi @robertodecurnex 

Thank you very much! It works perfectly now.

**Comment by robertodecurnex** [comment]
Btw, you can also go the CDN path, just keep the ng2-material version
updated on the URL.

http://plnkr.co/edit/d83ZQIAemyA40OhE3vYI?p=preview

**Comment by geelus** [comment]
Sure. Thanks.

**Comment by sysmat** [comment]
Hi @robertodecurnex I try your solution, but getting error:

angular2-polyfills.js:332 Error: TypeError: require is not a function
	    at eval (http://localhost:3000/node_modules/ng2-material/all.js:5:14)
	    at eval (http://localhost:3000/node_modules/ng2-material/all.js:87:3)
	    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:332:29)
	Evaluating http://localhost:3000/node_modules/ng2-material/all.js
	Error loading http://localhost:3000/node_modules/ng2-material/all.js as "ng2-material/all" from http://localhost:3000/app/main.js

**Comment by Skylar92** [comment]
+1
I have similar error.
My dependency list
"dependencies": {
    "angular2": "2.0.0-beta.14",
    "systemjs": "0.19.25",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6",
    "ng2-material": "0.3.5"
  }

**Comment by Tadimsky** [comment]
Any update on how to get this working?
Seeing the same `Unhandled Promise rejection: ReferenceError: require is not defined` error.

**Comment by justindujardin** [comment]
The NPM package `0.4.1` should resolve this issue. Please re-open if you continue to have problems with the latest version.

**Comment by JashaadGaines** [comment]
I got this problem while trying to run karma angular2 tests in karma. Can anyone explain the underlying problem & solution in more detail so I can possibly apply it to my issue as well.
