### ISSUE TITLE
md-input-container not working

### ISSUE THREAD

**Issue by donotdont** [justindujardin/ng2-material#11]
i use md-input-container 2 tag(html) like this
```html
        <md-input-container>
            <input class="md-input" />
        </md-input-container>
        <md-input-container>
            <textarea class="md-input"></textarea>
        </md-input-container>
```
,  it's not working.
![image](https://cloud.githubusercontent.com/assets/1459713/12175024/7de5d29a-b592-11e5-8a05-f4cdd26c5ab1.png)

**Comment by busbina** [comment]
I fixed this last night. Ill push it up. I am working with the inputs currently, am I stepping on anyone's toes?

**Comment by busbina** [comment]
Pull request #12.

**Comment by donotdont** [comment]
Thank you very much. Can you pull to npm? because i not use typescript, i see it's generate to js automatic when npm install or update. i don't know How's to convert file '.ts' to '.js'. i try convert by typescriptlang.org/Playground. it's not working.

**Comment by donotdont** [comment]
Thank you very much.
