### ISSUE TITLE
Heads up: @View has been obsoleted

### ISSUE THREAD

**Issue by MilosStanic** [justindujardin/ng2-material#111]
Hi @justindujardin 
It has come to my attention that in the latest PR of Angular2, @View decorator has been obsoleted. 
It has been optional until now, but now it is out. 

So everything you have in @View should be moved to @Component decorator.

**Comment by justindujardin** [comment]
Thanks for the heads up!

Will you (or someone) please open a PR to update all the components with this change?  I'm really busy at work and might not have time for this until next week.

**Comment by MilosStanic** [comment]
here you go https://github.com/justindujardin/ng2-material/pull/112
