### ISSUE TITLE
Make SidenavService optional

### ISSUE THREAD

**Issue by KlausConrado** [justindujardin/ng2-material#114]
Hi.

I'm using MdSidenav directly with @ChildView because the SidenavService doesn't provide a "toggle" method. This way, the SidenavService is not useful at all, but i'm still obligated to declare it as a provider.

I think that the SidenavService should be an optional injection in the MdSidenav, avoiding the "register" and "unregister" if it was not provided.

Thanks!

**Comment by justindujardin** [comment]
The sidenav service has been replaced by the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.
