### ISSUE TITLE
TypeError: dom_adapter_1.DOM is null

### ISSUE THREAD

**Issue by janispritzkau** [justindujardin/ng2-material#118]
This error comes every time the static canApply() function in the ink.js file is executed.
`import {DOM} from "angular2/src/platform/dom/dom_adapter";`

Ink class:
```
static canApply(element: HTMLElement): boolean {
    return !DOM.hasAttribute(element, 'md-no-ink');
}
```
I am using angular2 2.0.0-beta.11, but in beta.9 it's the same.

I found a way to fix this:
`import {BrowserDomAdapter} from "angular2/src/platform/browser/browser_adapter";`
and in the class:
`dom: BrowserDomAdapter = new BrowserDomAdapter();`
and then use `this.dom` instead of `DOM`.

**Comment by justindujardin** [comment]
@janispritzkau are you executing in a non-browser environment? e.g. using universal and node?

**Comment by christaime** [comment]
@janispritzkau Thank for your solution. It comes in handy!
Working with angular2@2.0.0-beta.14 and facing same issue.

**Comment by justindujardin** [comment]
Package `0.4.1` does not use the DOM adapter anymore. Closing this issue.
