### ISSUE TITLE
not able start the project

### ISSUE THREAD

**Issue by nishantgirbar** [justindujardin/ng2-material#125]
I have downloaded the zip file, and did npm install which installed all the dependencies, please below package entry

 "scripts": {
    "test": "npm install",
     "start": "grunt serve --force"
  }

but when i am trying to npm start then i am facing problem that 
1. ts:source failed
2. You need to have Ruby and Sass installed and in your PATH for this task to work

Thanks,
Nishant Kumar

**Comment by Gregcop1** [comment]
Using `grunt-sass` instead of `grunt-contrib-sass` will increase the speed of build and will remove the dependency to Ruby

**Comment by Gregcop1** [comment]
There's a PR #124 about fixing package.json scripts

For the ts:source part, I don't know

**Comment by axal90** [comment]
I'm closing this issue.
Feel free to reopen if it is still an issue.
