### ISSUE TITLE
Issue with md-sidenav Angular 2.0.0-beta.11 - No provider for SidenavService! (MdSidenav -> SidenavService)

### ISSUE THREAD

**Issue by shameerkc** [justindujardin/ng2-material#126]
While using md-sidenav tag, the problem is seen.

`angular2.dev.js:23730 Error: Uncaught (in promise): No provider for SidenavService! (MdSidenav -> SidenavService)
    at resolvePromise (angular2-polyfills.js:534)
    at angular2-polyfills.js:570
    at ZoneDelegate.invokeTask (angular2-polyfills.js:355)
    at Object.onInvokeTask (angular2.dev.js:2208)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:354)
    at Zone.runTask (angular2-polyfills.js:254)
    at drainMicroTaskQueue (angular2-polyfills.js:473)
    at XMLHttpRequest.ZoneTask.invoke (angular2-polyfills.js:425)`

EXCEPTION: No provider for SidenavService! (MdSidenav -> SidenavService)
angular2.dev.js:23730 EXCEPTION: No provider for SidenavService! (MdSidenav -> SidenavService)BrowserDomAdapter.logError @ angular2.dev.js:23730BrowserDomAdapter.logGroup @ angular2.dev.js:23741ExceptionHandler.call @ angular2.dev.js:1292(anonymous function) @ angular2.dev.js:12812ZoneDelegate.invoke @ angular2-polyfills.js:322onInvoke @ angular2.dev.js:2216ZoneDelegate.invoke @ angular2-polyfills.js:321Zone.run @ angular2-polyfills.js:218(anonymous function) @ angular2-polyfills.js:567ZoneDelegate.invokeTask @ angular2-polyfills.js:355onInvokeTask @ angular2.dev.js:2208ZoneDelegate.invokeTask @ angular2-polyfills.js:354Zone.runTask @ angular2-polyfills.js:254drainMicroTaskQueue @ angular2-polyfills.js:473ZoneTask.invoke @ angular2-polyfills.js:425
main.ts:7 NoProviderError {message: "No provider for SidenavService! (MdSidenav -> SidenavService)", stack: "Error: DI Exception↵    at NoProviderError.BaseExc…larjs.org/2.0.0-beta.11/angular2.dev.js:11059:19)", keys: Array[2], injectors: Array[2]}(anonymous function) @ main.ts:7ZoneDelegate.invoke @ angular2-polyfills.js:322Zone.run @ angular2-polyfills.js:218(anonymous function) @ angular2-polyfills.js:567ZoneDelegate.invokeTask @ angular2-polyfills.js:355Zone.runTask @ angular2-polyfills.js:254drainMicroTaskQueue @ angular2-polyfills.js:473ZoneTask.invoke @ angular2-polyfills.js:425

**Comment by ollwenjones** [comment]
Need more detail. Maybe a plunkr duplicating the issue.

**Comment by shameerkc** [comment]
I'm sorry, I realized the problem very soon, that I had created two instances of the object via bootstrapping as well as provider. No fixes are required and sorry for raising the issue...
