### ISSUE TITLE
SCSS compile fails

### ISSUE THREAD

**Issue by tobakk** [justindujardin/ng2-material#127]
node_modules/ng2-material/source/core/style/layout.scss
Error: Invalid CSS after "  @media screen": expected "{", was "\\0"
        on line 170 of node_modules/ng2-material/source/core/style/layout.scss
>>   @media screen \0

My SASS build fails after update to 0.2.12

There is a \0 in layout.scss - when you remove it manually it will compile again.

**Comment by Gregcop1** [comment]
Same as #122

**Comment by justindujardin** [comment]
Sorry this took a while, 0.2.13 is published to NPM now.
