### ISSUE TITLE
Input:Select

### ISSUE THREAD

**Issue by diamo1213** [justindujardin/ng2-material#128]
Hi guys,

select elements doesn't look in material design: https://www.dropbox.com/s/dgj0cb27v4bisc0/Screenshot%202016-03-24%2014.23.50.png?dl=0

Will it be fixed?

Thanx

**Comment by sylvaindumont** [comment]
Unless someone want to develop this component, no. See #67 

I personally give select an input aspect with : 

```
select {
  border: none;
  border-bottom: 1px solid rgba(0, 0, 0, 0.12);
  padding: 2px;
  text-transform: capitalize;
}

select:focus {
  outline: none;
  border-color: #3f51b5;
  border-width: 2px;
}
```

It doesn't follow the spec, but it integrates with the others inputs.

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
