### ISSUE TITLE
Invalid imports when using "angular2" inside "dependencies" (package.json)

### ISSUE THREAD

**Issue by dotansimha** [justindujardin/ng2-material#131]
Hi,

Tried to use this package with Meteor 1.3 and load it from NPM - is causes a lot of weird error because Angular 2 is a explicit dependency of this package:
https://github.com/justindujardin/ng2-material/blob/master/package.json#L16-L17

Instead of using "dependencies" section, it should use "peerDependencies" in order to make sure that Angular 2 is loaded only once in the project (once from /node_modules/ and once from /node_modules/ng2-material/node_modules/) - otherwise there are two injectors  and it is impossible to access the registered directives.

**Comment by justindujardin** [comment]
@dotansimha thanks for mentioning it.

It's a bit unclear, but as part of the build for publishing to NPM, the dependencies are swapped with peerDependencies so that you get them as peerDependencies when you install.
