### ISSUE TITLE
angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by rezss** [justindujardin/ng2-material#132]
Good day to you,

i tried ng2-material for the first time but get welcomed with the following error:

`angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <`

as soon as i either use the directive [MATERIAL_DIRECTIVES] or the provider [MATERIAL_PROVIDERS].

```
angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/ng2-material/all
	Error loading http://localhost:3000/app/main.jsZoneDelegate.invoke @ angular2-polyfills.js:332
````

````
import {Component} from 'angular2/core';
import {MATERIAL_DIRECTIVES} from 'ng2-material/all';

@Component({
  selector: 'my-app',
  templateUrl: 'app/app.template.html',
  directives: [MATERIAL_DIRECTIVES]
  // providers: [MATERIAL_PROVIDERS]
})
export class AppComponent {
  clicked(name: string) {
    console.log(name);
  }
}

```

Edit: 
````
  "dependencies": {
    "angular2": "2.0.0-beta.12",
    "bootstrap": "^3.3.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "ng2-material": "^0.2.12",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.24",
    "zone.js": "0.6.6"
  },
````

**Comment by geelus** [comment]
It is so frustrating that any time I want to test this, it's always broken! Is anybody even using this???

Here is the bug details:
angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <(…)
----------------------------------------------------------------------------------------
ZoneDelegate.invoke	@	angular2-polyfills.js:332
Zone.run	@	angular2-polyfills.js:227
(anonymous function)	@	angular2-polyfills.js:576
ZoneDelegate.invokeTask	@	angular2-polyfills.js:365
Zone.runTask	@	angular2-polyfills.js:263
drainMicroTaskQueue	@	angular2-polyfills.js:482
ZoneTask.invoke	@	angular2-polyfills.js:434
XMLHttpRequest.send (async)		
fetchTextFromURL	@	system.src.js:1085
(anonymous function)	@	system.src.js:1646
ZoneAwarePromise	@	angular2-polyfills.js:589
(anonymous function)	@	system.src.js:1645
(anonymous function)	@	system.src.js:2667
(anonymous function)	@	system.src.js:3239
(anonymous function)	@	system.src.js:3506
(anonymous function)	@	system.src.js:3888
(anonymous function)	@	system.src.js:4347
(anonymous function)	@	system.src.js:4599
(anonymous function)	@	system.src.js:337
ZoneDelegate.invoke	@	angular2-polyfills.js:332
Zone.run	@	angular2-polyfills.js:227
(anonymous function)	@	angular2-polyfills.js:576
ZoneDelegate.invokeTask	@	angular2-polyfills.js:365
Zone.runTask	@	angular2-polyfills.js:263
drainMicroTaskQueue	@	angular2-polyfills.js:482
ZoneTask.invoke	@	angular2-polyfills.js:434
XMLHttpRequest.send (async)		
fetchTextFromURL	@	system.src.js:1085
(anonymous function)	@	system.src.js:1646
ZoneAwarePromise	@	angular2-polyfills.js:589
(anonymous function)	@	system.src.js:1645
(anonymous function)	@	system.src.js:2667
(anonymous function)	@	system.src.js:3239
(anonymous function)	@	system.src.js:3506
(anonymous function)	@	system.src.js:3888
(anonymous function)	@	system.src.js:4347
(anonymous function)	@	system.src.js:4599
(anonymous function)	@	system.src.js:337
ZoneDelegate.invoke	@	angular2-polyfills.js:332
Zone.run	@	angular2-polyfills.js:227
(anonymous function)	@	angular2-polyfills.js:576
ZoneDelegate.invokeTask	@	angular2-polyfills.js:365
Zone.runTask	@	angular2-polyfills.js:263
drainMicroTaskQueue	@	angular2-polyfills.js:482
ZoneTask.invoke	@	angular2-polyfills.js:434
XMLHttpRequest.send (async)		
fetchTextFromURL	@	system.src.js:1085
(anonymous function)	@	system.src.js:1646
ZoneAwarePromise	@	angular2-polyfills.js:589
(anonymous function)	@	system.src.js:1645
(anonymous function)	@	system.src.js:2667
(anonymous function)	@	system.src.js:3239
(anonymous function)	@	system.src.js:3506
(anonymous function)	@	system.src.js:3888
(anonymous function)	@	system.src.js:4347
(anonymous function)	@	system.src.js:4599
(anonymous function)	@	system.src.js:337
ZoneDelegate.invoke	@	angular2-polyfills.js:332
Zone.run	@	angular2-polyfills.js:227
(anonymous function)	@	angular2-polyfills.js:576
ZoneDelegate.invokeTask	@	angular2-polyfills.js:365
Zone.runTask	@	angular2-polyfills.js:263
drainMicroTaskQueue	@	angular2-polyfills.js:482
$	@	system-polyfills.src.js:1340
H	@	system-polyfills.src.js:1340
R.when	@	system-polyfills.src.js:1340
T.run	@	system-polyfills.src.js:1340
t._drain	@	system-polyfills.src.js:1340
drain	@	system-polyfills.src.js:1340
e	@	system-polyfills.src.js:1340
Mutation (async)		
(anonymous function)	@	system-polyfills.src.js:1340
t.run	@	system-polyfills.src.js:1340
t.enqueue	@	system-polyfills.src.js:1340
g.when	@	system-polyfills.src.js:1340
j.chain	@	system-polyfills.src.js:1340
e.then	@	system-polyfills.src.js:1340
scheduleQueueDrain	@	angular2-polyfills.js:455
scheduleMicroTask	@	angular2-polyfills.js:463
ZoneDelegate.scheduleTask	@	angular2-polyfills.js:348
Zone.scheduleMicroTask	@	angular2-polyfills.js:280
scheduleResolveOrReject	@	angular2-polyfills.js:574
ZoneAwarePromise.then	@	angular2-polyfills.js:649
(anonymous function)	@	system.src.js:4557
Loader.import	@	system.src.js:801
(anonymous function)	@	system.src.js:1669
(anonymous function)	@	(index):49

**Comment by robertodecurnex** [comment]
Duplicated
#108

**Comment by justindujardin** [comment]
The NPM package `0.4.1` should support webpack bundling properly. Closing this issue.
