### ISSUE TITLE
 MdDataTable tr uses a tr tag selector

### ISSUE THREAD

**Issue by wallace41290** [justindujardin/ng2-material#134]
This is causing a name-space issue when trying to use a <tr> element. It will result in an EXCEPTION: No provider for MdDataTable! (MdDataTableTr -> MdDataTable). I suggest changing the selector to avoid conflicts in data_table_tr.ts

**Comment by szechyjs** [comment]
Duplicate of #133

**Comment by justindujardin** [comment]
Fixed with 0.3.4, and deployed to npm.
