### ISSUE TITLE
Select dropdown not rendering correctly on OS X in Chrome

### ISSUE THREAD

**Issue by MarkPieszak** [justindujardin/ng2-material#136]
OS X 10.11.4 Chrome (latest)
Showing up as the normal Dropdown for some reason.

![image](https://cloud.githubusercontent.com/assets/2574412/14089286/2ca21862-f502-11e5-896f-072c6dfa38c1.png)

**Comment by ollwenjones** [comment]
Same on Chrome Windows 10... it's been that way, and I just never paid attention.

![md_select](https://cloud.githubusercontent.com/assets/1319208/14115468/2276bb3e-f5a9-11e5-9934-f55de4c587bd.png)

**Comment by ollwenjones** [comment]
This duplicates #128

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  

The select component is not implemented, but the confusion should be removed as it is no longer in a demo. Closing this issue.
