### ISSUE TITLE
Cannot find source file(s)

### ISSUE THREAD

**Issue by shawnrmoss** [justindujardin/ng2-material#139]
Ive followed your instructions and added your components to an angular2 webpack project.  Ive added the directives, providers and css with no problem.  But in the console when I load the page I get warning from webpack-dev-server saying it cannot find a bunch of files.  

./~/ng2-material/components/button/button.js
Cannot find source file 'ng2-material//components/button/button.ts': Error: Cannot resolve 'file' or 'directory' ./ng2-material//components/button/button.ts in C:\fm\ateles\node_modules\ng2-material\components\button

Any help would be great!

**Comment by axal90** [comment]
Have you looked in the directory?
Is the file there?
If it isnt, you should reinstall the package.
if it is then something else is wrong.

**Comment by ojacquemart** [comment]
I got the same issue.

Here is the message if it can help:

```
/~/ng2-material/all.js
Cannot find source file 'ng2-material//all.ts': Error: Cannot resolve 'file' or 'directory' ./ng2-material//all.ts in /home/olivier/dev/workspaces/ngular2-webpack-starter/node_modules/ng2-material
...
/~/ng2-material/components/dialog/dialog_config.js
Cannot find source file 'ng2-material//components/dialog/dialog_config.ts': Error: Cannot resolve 'file' or 'directory' ./ng2-material//components/dialog/dialog_config.ts in /home/olivier/dev/workspaces/angular2-webpack-starter/node_modules/ng2-material/components/dialog
```

Indeed, the files listed as warning are not present. I tried to reinstall the package.
Any ideas?

**Comment by radostyle** [comment]
I also got this, though it still seems to work.  It happens on a webpack project I integrated it into, though it doesn't seem to happen on the System.js projects I've seen.

**Comment by gvandyk-r7** [comment]
+1 I am receiving these errors as well

**Comment by rpatterson** [comment]
Root issue is the wrong `sourceRoot` in the source maps:

    $ find node_modules/ng2-material/ -name all.ts
    node_modules/ng2-material/source/all.ts
    $ python -c "import json; print json.load(open('node_modules/ng2-material/all.js.map'))['sourceRoot']"
    ng2-material/

**Comment by justindujardin** [comment]
The `0.4.1` npm package should resolve source maps properly. Please re-open if it still does not work for you with the latest version.
