### ISSUE TITLE
textarea multirow

### ISSUE THREAD

**Issue by MilosStanic** [justindujardin/ng2-material#141]
Textarea doesn't resize when you specify `rows` property. It's visible even in the demo page. The `rows` was specified to 5, but it is single row, nevertheless.

**Comment by axal90** [comment]
Untill its fixed you can use css to specify the height you want.

For styling guides.
https://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
