### ISSUE TITLE
md-sidenav overlays outside of the md-sidenavcontainer

### ISSUE THREAD

**Issue by tzejohn** [justindujardin/ng2-material#145]
I was using the md-sidenav and the slide out was overlapping over the whole window instead of just the section the parent container is in, like in the [example page](https://justindujardin.github.io/ng2-material/#/components/sidenav).  I created a plunk to show what I mean.  What I want to happen is for the slide out to not overlay on top of the toolbar.   Is there something I am missing?

http://plnkr.co/edit/y4gsxX7gPFUnKjWlMjai?p=preview

**Comment by axal90** [comment]
Some simple css will solve your problem
```
md-toolbar {
  z-index: 99;
}
```

**Comment by tzejohn** [comment]
That would solve it for this case.. but I am trying to figure out why when I inspect the ng2-material example page, the side navs are sized to the container, whereas in my case they are sized to the whole body content. I tried to go through the css on the example page, but I can't seem to figure it out.

**Comment by axal90** [comment]
`transform: translate3D(0, 0, 0);`

that is the secret! :)
Put it on the cotainer of the md-sidenav-container.
[Updated your plunker](http://plnkr.co/edit/iVUmhf5z8F28ajbbTmDE?p=preview)

I just started using this project some days ago, so new to the code :p 
Took me some time to dive into the code.
Hope it helps.

**Comment by tzejohn** [comment]
Thanks @axal90 that works. I will assume it is some kind of hack, since the transform isn't really transforming anything, and something must be getting rendered differently with the hardware acceleration  enabled.

**Comment by ollwenjones** [comment]
Should we add `transform: translate3D(0, 0, 0);` to the `md-sidenav-container` CSS, so that is handled already, or would that have unexpected side-effects?

**Comment by axal90** [comment]
I would say that md-sidenav-container should contain the sidenav as default behavior. 
If not a name change would be the right thing to do. :p
As to side-effects, I'm not really qualyfied to comment on that, but if I get time, I can try to do some research later today.

**Comment by ollwenjones** [comment]
I was thinking of something unintended, like adding that translate3D to keep it's child sidenav in the right spot also cause it to modify where a dialog or some other user component shows up? I guess those things shouldn't be children of the `md-sidenav-container` though...

**Comment by justindujardin** [comment]
I'm planning to start deprecating components (not their examples) and using the official ones as they're available and stable. If you check out the `material2` branch, I already have most of the sidenav replaced.

The material2 sidenav is pretty nice, and takes into consideration the issues you guys are talking about. [Check out their design doc](https://docs.google.com/document/d/1baTbj5OOkUMpwRLDo23sLMVl5ZQtk8-RgpiL2zTuoUk/edit)

**Comment by justindujardin** [comment]
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.
