### ISSUE TITLE
Use renderer instead to interact with dom to allow for server side rendering

### ISSUE THREAD

**Issue by axal90** [justindujardin/ng2-material#146]
Currently getting this error with one component.
```
E:\node\msls2\node_modules\ng2-material\core\util\animate.js:88
        var el = document.createElement('fakeelement');
                 ^

ReferenceError: document is not defined
    at Function.Animate.whichTransitionEvent (E:\node\msls2\node_modules\ng2-material\core\util\animate.js:88:18)
    at E:\node\msls2\node_modules\ng2-material\core\util\animate.js:151:40
    at Object.<anonymous> (E:\node\msls2\node_modules\ng2-material\core\util\animate.js:153:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\node\msls2\node_modules\ng2-material\core\util\ink.js:4:17)
```

Example from a starter pack:
```
import {ElementRef, Renderer} from 'angular2/core';

@Directive({
  selector: '[large-text]'
})
export class LargeText {
  constructor(element: ElementRef, renderer: Renderer) {
    // we must interact with the dom through Renderer for webworker/server to see the changes
    renderer.setElementStyle(element.nativeElement, 'fontSize', '80');
  }
}
```
https://github.com/angular/universal

**Comment by justindujardin** [comment]
@axal90 I have an unfinished [universal](https://github.com/justindujardin/ng2-material/tree/universal) branch of the repo you could look at. I'd welcome help getting that branch finished up for merging and release.

**Comment by axal90** [comment]
@justindujardin Great work!
Maybe bumb the version after breaking changes? 

I keep getting this error:
`Rendering Document Error: { [Error: EXCEPTION: Error during instantiation of MdSidenav!.
ORIGINAL EXCEPTION: This method is not implemented in Parse5DomAdapter: query
ORIGINAL STACKTRACE:
Error: This method is not implemented in Parse5DomAdapter: query
    at new BaseException (E:\node\msls2\node_modules\angular2\src\facade\exceptions.js:16:23)
    at _notImplemented (E:\node\msls2\node_modules\angular2\src\platform\server\parse5_adapter.js:25:12)
    at Parse5DomAdapter.query (E:\node\msls2\node_modules\angular2\src\platform\server\parse5_adapter.js:63:68)
    at MdSidenav.MdBackdrop (E:\node\msls2\node_modules\ng2-material\components\backdrop\backdrop.js:28:40)
    at new MdSidenav (E:\node\msls2\node_modules\ng2-material\components\sidenav\sidenav.js:67:16)
    at E:\node\msls2\node_modules\angular2\src\core\reflection\reflection_capabilities.js:19:59
    at Injector._instantiate (E:\node\msls2\node_modules\angular2\src\core\di\injector.js:786:27)
    at Injector._instantiateProvider (E:\node\msls2\node_modules\angular2\src\core\di\injector.js:715:25)
    at Injector._new (E:\node\msls2\node_modules\angular2\src\core\di\injector.js:704:21)
    at InjectorInlineStrategy.instantiateProvider (E:\node\msls2\node_modules\angular2\src\core\di\injector.js:204:30)
ERROR CONTEXT:
[object Object]]
  _wrapperMessage: 'DI Exception',
  _originalException:
   { [Error: This method is not implemented in Parse5DomAdapter: query]
     message: 'This method is not implemented in Parse5DomAdapter: query',
     stack: 'Error: This method is not implemented in Parse5DomAdapter: query\n    at new BaseException (E:\\node\\msls2\\node_modules\\angular2\\src\\facade\\exceptions.js:16:23)\n    at _notImplemented (E:\\node\\msls2\\node_modules\\angular2\\src\\platform\\serv
er\\parse5_adapter.js:25:12)\n    at Parse5DomAdapter.query (E:\\node\\msls2\\node_modules\\angular2\\src\\platform\\server\\parse5_adapter.js:63:68)\n    at MdSidenav.MdBackdrop (E:\\node\\msls2\\node_modules\\ng2-material\\components\\backdrop\\backdrop.js:28:40)
\n    at new MdSidenav (E:\\node\\msls2\\node_modules\\ng2-material\\components\\sidenav\\sidenav.js:67:16)\n    at E:\\node\\msls2\\node_modules\\angular2\\src\\core\\reflection\\reflection_capabilities.js:19:59\n    at Injector._instantiate (E:\\node\\msls2\\node
_modules\\angular2\\src\\core\\di\\injector.js:786:27)\n    at Injector._instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:715:25)\n    at Injector._new (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:704:
21)\n    at InjectorInlineStrategy.instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:204:30)' },
  _originalStack: 'Error: This method is not implemented in Parse5DomAdapter: query\n    at new BaseException (E:\\node\\msls2\\node_modules\\angular2\\src\\facade\\exceptions.js:16:23)\n    at _notImplemented (E:\\node\\msls2\\node_modules\\angular2\\src\\platform
\\server\\parse5_adapter.js:25:12)\n    at Parse5DomAdapter.query (E:\\node\\msls2\\node_modules\\angular2\\src\\platform\\server\\parse5_adapter.js:63:68)\n    at MdSidenav.MdBackdrop (E:\\node\\msls2\\node_modules\\ng2-material\\components\\backdrop\\backdrop.js:
28:40)\n    at new MdSidenav (E:\\node\\msls2\\node_modules\\ng2-material\\components\\sidenav\\sidenav.js:67:16)\n    at E:\\node\\msls2\\node_modules\\angular2\\src\\core\\reflection\\reflection_capabilities.js:19:59\n    at Injector._instantiate (E:\\node\\msls2
\\node_modules\\angular2\\src\\core\\di\\injector.js:786:27)\n    at Injector._instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:715:25)\n    at Injector._new (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.j
s:704:21)\n    at InjectorInlineStrategy.instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:204:30)',
  _context: null,
  _wrapperStack: 'Error: DI Exception\n    at InstantiationError.WrappedException [as constructor] (E:\\node\\msls2\\node_modules\\angular2\\src\\facade\\exceptions.js:33:31)\n    at new InstantiationError (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\ex
ceptions.js:137:16)\n    at Injector._instantiate (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:841:19)\n    at Injector._instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:715:25)\n    at Injector._new (
E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:704:21)\n    at InjectorInlineStrategy.instantiateProvider (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\di\\injector.js:204:30)\n    at ElementDirectiveInlineStrategy.init (E:\\node\\msls2\
\node_modules\\angular2\\src\\core\\linker\\element.js:558:24)\n    at new AppElement (E:\\node\\msls2\\node_modules\\angular2\\src\\core\\linker\\element.js:235:28)\n    at viewFactory_ServerAppComponent0 (viewFactory_ServerAppComponent:367:31)\n    at viewFactory
_Html0 (viewFactory_Html:236:1)',
  keys: [ Key { token: [Function: MdSidenav], id: 114 } ],
  injectors:
   [ Injector {
       _isHostBoundary: false,
       _depProvider: [Object],
       _debugContext: [Function],
       _constructionCounter: 1,
       _proto: [Object],
       _parent: [Object],
       _strategy: [Object] } ] }
`

**Comment by justindujardin** [comment]
I made some progress on this. I'll try to finish it up over the coming weekend.

**Comment by justindujardin** [comment]
@axal90 please try with 0.3.5 on npm and let me know if you have more success.

**Comment by justindujardin** [comment]
Closing for now, please re-open if you still encounter errors with ng2-material and universal.
