### ISSUE TITLE
Supporting Dynamic Forms

### ISSUE THREAD

**Issue by shameerkc** [justindujardin/ng2-material#151]
Just wondering if it would be possible to support dynamic forms.

The form controller sets some classes internally when dynamic forms are created and validated. When I use ng2-material with these, the styling is getting messed up.

I will provide a plunkr example soon.

https://angular.io/docs/ts/latest/guide/forms.html

State	Class if true	Class if false
Control has been visited	ng-touched	ng-untouched
Control's value has changed	ng-dirty	ng-pristine
Control's value is valid	ng-valid	ng-invalid

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
