### ISSUE TITLE
not compatibale with beta 10 -> 13

### ISSUE THREAD

**Issue by yahyaKacem** [justindujardin/ng2-material#152]
Hi, thanks for this, try your [plunker example](http://plnkr.co/edit/d83ZQIAemyA40OhE3vYI?p=preview) from [the official site](https://justindujardin.github.io/ng2-material/) and change the angular version to 10, 11, 12 or 13, the current example works with version 7, you can increment the version to 9 it will work, but from 10 to 13 I receive that error:
> Uncaught TypeError: core_1.View is not a function

**Comment by justindujardin** [comment]
You are using an outdated version of ng2-material then.  The latest versions do not use the deprecated View decorator. Please update your npm package version for ng2-material.

**Comment by werwuifi** [comment]
Hi, I am using ng2-material version 0.3.8 (from npm) and got a similar error. Here is the log:

> Failed to load resource: net::ERR_EMPTY_RESPONSE (20:23:45:754 | error, network)
>   at http://localhost:8383/favicon.ico
> Uncaught TypeError: core_1.View is not a function (20:23:45:987 | error, javascript)
>   at https://cdn.rawgit.com/justindujardin/ng2-material/410d0dc/ng2-material/components/button/button.js:53
> Uncaught Uncaught TypeError: core_1.View is not a function
> 	Evaluating https://cdn.rawgit.com/justindujardin/ng2-material/410d0dc/ng2-material/components/button/button.js (20:23:46:012 | error, javascript)
>   at https://code.angularjs.org/tools/system.js:4
> Script error.
> 	Evaluating https://cdn.rawgit.com/justindujardin/ng2-material/410d0dc/ng2-material/all.js
> 	Error loading http://localhost:8383/frontend/app/boot.ts (20:23:46:028 | error)
>   at node_modules/angular2/bundles/angular2-polyfills.js:332

Can anyone help me with this?
Cheers
w

**Comment by justindujardin** [comment]
@werwuifi it looks like you're including a CDN build of ng2-material as well.  Look for and remove the <script> tag that links to `https://cdn.rawgit.com/justindujardin/ng2-material/410d0dc/`, or look at your system.config to make sure it's not pointing at that url.

**Comment by werwuifi** [comment]
that's it, thx a lot!!
