### ISSUE TITLE
md-input not updated when putting data in with typescript

### ISSUE THREAD

**Issue by yahyaKacem** [justindujardin/ng2-material#153]
Hi, I'm trying to do an edit form with ng2-material, but I'm having this problem with the md-input when I update the value with the data from the model most of the data get assigned but the state of the md-input stay the same (the label doesn't shrink to the top corner like it should), also some other input doesn't get updated, at all, but only in the view, if I log the value of the form I get all the data there, check this [plunker](http://plnkr.co/edit/Yf2WgO47EcPryMJY3J9w?p=preview) with a working non material example, and [this plunker for the error](http://plnkr.co/edit/mSKq0OuNlrJukQV0pwz0?p=preview).

**Comment by ollwenjones** [comment]
Relates to #100 if not a duplicate.

**Comment by yahyaKacem** [comment]
@ollwenjones I don't see how this is related to #100 I get the validation working correctly the values are in the form.value as it's seend better in this [plunker](http://plnkr.co/edit/LbLrlfz9AGHMPPS1KB2l?p=preview), but the `md-input-container` doen't take the class `md-input-has-value` until the input is touched.
So I get the values in the inputs when I click them I see the values there, but when I blur out without any key press the input goes back to having it's label on top of it, even though there's a value in it.
please check [plunker](http://plnkr.co/edit/LbLrlfz9AGHMPPS1KB2l?p=preview).

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
