### ISSUE TITLE
Updating dependencies break tests

### ISSUE THREAD

**Issue by blacknight811** [justindujardin/ng2-material#158]
I updated my dependencies to the following: 
```
dependencies": {
    "angular2": "2.0.0-beta.12",
    "es6-module-loader": "^0.17.8",
    "es6-shim": "^0.35.0",
    "ng2-material": "^0.1.0",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.4",
    "zone.js": "^0.6.6"
  }
```

After the test are failing. Going into karma.conf.js and changing
```
// list of files / patterns to load in the browser
    files: [
      'node_modules/zone.js/dist/zone-microtask.js',
```
to
```
// list of files / patterns to load in the browser
    files: [
      'node_modules/zone.js/dist/zone.js',
```
fixes most of them. But still stuck with 
```
app/components/about/about_spec.ts(8,20): error TS2305: Module '"/Users/bknight/projects/cf/stock-seed/node_modules/angular2/core"' has no exported member 'View'.
app/components/about/about_spec.ts(22,53): error TS2339: Property 'componentViewChildren' does not exist on type 'DebugElement'.
app/components/about/about_spec.ts(23,50): error TS2339: Property 'componentViewChildren' does not exist on type 'DebugElement'.
app/components/app/app_spec.ts(9,20): error TS2305: Module '"/Users/bknight/projects/cf/stock-seed/node_modules/angular2/core"' has no exported member 'View'.
app/components/app/app_spec.ts(37,48): error TS2339: Property 'componentViewChildren' does not exist on type 'DebugElement'.
app/components/home/home_spec.ts(8,20): error TS2305: Module '"/Users/bknight/projects/cf/stock-seed/node_modules/angular2/core"' has no exported member 'View'.
app/components/home/home_spec.ts(19,49): error TS2339: Property 'componentViewChildren' does not exist on type 'DebugElement'.
```

and
```
08 04 2016 11:59:07.159:WARN [web-server]: 404: /base/selenium-webdriver.js
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?18a094f61af9f2ec0577ca3a337760d97719b624'}
08 04 2016 11:59:07.643:WARN [web-server]: 404: /base/selenium-webdriver.js
ERROR: Error{originalErr: Error{}}
```
I think that the Angular API changed to remove 'View' from angular2/core so I can fix this by moving the View metadata into the Component metadata. I looked at DebugElement and it indeed no longer exports 'componentViewChildren' and I can't find it anywhere in the codebase so I assume it's been removed. I just don't know what is the equivalent replacement code for this. 

And I don't know what's causing the selenium / PhantomJS Error at all. 

Any ideas? I'm using this at my job and need to get it fixed. 

P.S. Not looking for you to fix this, just some guidance into how to fix it myself and then I can put in a PR if others want to use it.

**Comment by blacknight811** [comment]
ok fixed all of the view and componentViewChildren errors. moved ```@View``` metadata in test up to ```@Component``` and removed ```@View``` and ```View``` from import statement. ```componentViewChildren``` was depricated in Beta 3 and you can replace this with ```children```. So now only left with selenium errors.

**Comment by justindujardin** [comment]
@blacknight811 you should update to the latest version of ng2-material.  It's currently at 0.3.5, which is greater than the 0.1.0 match you have.
