### ISSUE TITLE
Poor performance with ng2-material on IE11

### ISSUE THREAD

**Issue by lelezeus88** [justindujardin/ng2-material#166]
Hello,
I noticed that with ng-material the performance on Internet Explorer 11 is dramatically slow while displaying 1500 different images. Seems that without ng-material the page is more responsive and faster during rendering.
Please have a look at the following plnkr:
- Without ng-material: [http://plnkr.co/edit/V8Bc9d2r1PDsF1JzTtoF?p=preview](url)
- With ng-material: [http://plnkr.co/edit/PBkZHGz9Qe8Egarrhs14?p=preview](url)

Anyone with the same issue? Any workaround or tip for improving performance?
Maybe I'm importing ng-material in the wrong way.

Thank you in advance.

**Comment by vifore** [comment]
I had same issue. I think layout css has low performance in IE11.
ng2-material css(maybe it comes from angular1 material) has inefficient layout codes, and it takes too much time for calculating and rendering .
Remove all layout related codes in css, and use flex manually.
I'm sorry for my poor English :)

**Comment by lelezeus88** [comment]
Thank you, you're right. Do you think that will be fixed for next releases?

**Comment by vladimir-ivanov** [comment]
also angular2 itself does not perform great in ie11, zone js is causing delays in rendering, pollyfill  - es6-shim make it slower, etc - see http://stackoverflow.com/questions/36570532/angular-2-performance-ie11-ngfor  for instance

**Comment by lelezeus88** [comment]
yes that was my post on stackoverflow :) fortunately with core-js (instead of es6-shim) the performance is better.  I think that with core-js and fixing css of ng2-material the performance is more or less acceptable on IE11.

**Comment by vladimir-ivanov** [comment]
core-js does not improve things for me much, still very poor performance when combining ng2-material with other third party libraries (ag-grid). 
Found that you can not isolate the zone.js tick() for setTimeout / other events not to be overwritten by the zone.
So we end up with all of the async methods still overwritten outside the angular2 code - and executing / triggering zone ticks.

**Comment by lelezeus88** [comment]
That could be a short term solution, in prospective I hope that Zone or Angular2 guys will find a solution, especially if your company is going to provide compatibility with IE11.

**Comment by vladimir-ivanov** [comment]
we are moving away form ie11, doubt it will be supported for much longer. Too much overhead to maintain it

**Comment by lelezeus88** [comment]
I tried with edge which is better than IE but not as fast as chrome.
I will try material2 instead of ng2-material to see if there are the same rendering problems with IE11.

**Comment by justindujardin** [comment]
I believe this is a problem with how IE deals with having a bunch of attributes on elements (for the flex layout stuff.)  The Angular1 material project had a service for converting those attributes into CSS class names to help performance in IE.

https://github.com/angular/material/blob/master/src/core/services/layout/layout.js#L54-L59

It's unlikely that I will port this code as I have no use for IE personally. I expect that when the material2 project is 1.0 it will support IE much better than this project.

I'm going to close this issue for now, but I've added the enhancement and help-wanted tags in case anyone needs to use IE and wants to do the work to submit a PR.
