### ISSUE TITLE
TypeError: all_2.Media.hasMedia is not a function

### ISSUE THREAD

**Issue by shirishparsekar** [justindujardin/ng2-material#167]
I am trying **Sidenav** as shown in the [demos](https://justindujardin.github.io/ng2-material/#/components/sidenav).

I am getting errors related to `Media.hasMedia` method:

`EXCEPTION: TypeError: _media.hasMedia is not a function in [hasMedia('gt-sm') ? 'side' : 'over' in AppComponent@17:32]`

`EXCEPTION: Error: Uncaught (in promise): EXCEPTION: TypeError: _media.hasMedia is not a function in [hasMedia('gt-sm') ? 'side' : 'over' in AppComponent@17:32]
ORIGINAL EXCEPTION: TypeError: _media.hasMedia is not a function
ORIGINAL STACKTRACE:
TypeError: _media.hasMedia is not a function
    at AppComponent.hasMedia (http://localhost:3000/app/app.component.js:68:35)
    at AbstractChangeDetector.ChangeDetector_AppComponent_0.detectChangesInRecordsInternal (viewFactory_AppComponent:114:31)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9609:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9592:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9671:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9596:12)
    at AbstractChangeDetector.detectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9581:12)
    at ChangeDetectorRef_.detectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5252:16)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12954:27
    at Array.forEach (native)
ERROR CONTEXT:
[object Object]`

and many similar errors.

I have imported `Media` from 'ng2-material/all' and have this in the component

`hasMedia(breakSize: string): boolean {
        let _media = Media;
        return _media.hasMedia(breakSize);
}`

**Comment by theunreal** [comment]
Same error

```
import { Component } from 'angular2/core';
import { Router, RouterLink } from 'angular2/router';
import { CORE_DIRECTIVES, FORM_DIRECTIVES } from 'angular2/common';
import {Http, Headers, Response, HTTP_PROVIDERS} from 'angular2/http';
import {JwtService} from './services/jwt.service';
import {MATERIAL_DIRECTIVES,MATERIAL_PROVIDERS,SidenavService, Media} from "ng2-material/all";

@Component({
  selector: 'member-page',
  directives: [RouterLink, CORE_DIRECTIVES, FORM_DIRECTIVES,MATERIAL_DIRECTIVES ],
  templateUrl: 'app/template/member-page.html',
  providers:[JwtService,MATERIAL_PROVIDERS, SidenavService],
})
export class MemberPageComponent implements OnInit {
	
	hasMedia(breakSize: string): boolean {
    return Media.hasMedia(breakSize);
  }
	
	open(name: string) {
    this.sidenav.show(name);
  }
  close(name: string) {
    this.sidenav.hide(name);
  }
  
  constructor(public router: Router, public http: Http, private JwtService:JwtService,public sidenav: SidenavService) {}
  
}
```

**Comment by shirishparsekar** [comment]
@theunreal you have provided a solution or you mean to say you have the same problem? please be clear

**Comment by theunreal** [comment]
@shirishparsekar  I have the same problem. btw, if you will remove the hasMedia method from yout template it will work, but not as excepted

**Comment by justindujardin** [comment]
Sorry, I need to deploy the updated example site for v0.3.5.  That method was removed to support node.js rendering.

https://github.com/justindujardin/ng2-material/blob/master/examples/components/sidenav/basic_usage.ts

**Comment by justindujardin** [comment]
Please see the example for 0.3.5: https://justindujardin.github.io/ng2-material/v/0.3.5/#/components/sidenav

**Comment by shirishparsekar** [comment]
@justindujardin whats the change in this example? is looks to be same as https://justindujardin.github.io/ng2-material/#/components/sidenav

**Comment by justindujardin** [comment]
The change is that the SidenavService is injected into the constructor, and then `this.media.hasMedia` is used in place of `Media.hasMedia`

```typescript
constructor(public sidenav: SidenavService,
              public media: Media) {

  }

  hasMedia(breakSize: string): boolean {
    return this.media.hasMedia(breakSize);
  }
```

**Comment by shirishparsekar** [comment]
I tried that but I got same error!

**Comment by shirishparsekar** [comment]
@justindujardin  I tried that and I got this error

> EXCEPTION: TypeError: Cannot read property 'matchMedia' of undefined in [hasMedia('gt-sm') ? 'side' : 'over' in AppComponent@17:36]
