### ISSUE TITLE
Error: XHR error (404 Not Found) loading http://localhost:9876/ng2-material/all

### ISSUE THREAD

**Issue by JDillon522** [justindujardin/ng2-material#168]
I'm building out a new Angular 2 app with the Alpha Angular-CLI. In order to even get ng2-material to work I had to do the following:

```
// index.html
System.config({
  packages: {
      app: {
          format: 'register',
          defaultExtension: 'js 
       },
      'ng2-material': {
          format: 'cjs',
          defaultExtension: 'js',
          main: 'all.js'
      }
  }
  });
  System.import('app.js').then(null, console.error.bind(console));

// ember-cli-build.js
var materialTree = BroccoliFunnel('node_modules/ng2-material', {
    destDir: 'ng2-material'
});
```

It works fine in the app itself. However, when I run ng test I get the following error:

```
START:

13 04 2016 14:55:36.982:WARN [web-server]: 404: /ng2-material/all

Chrome 49.0.2623 (Mac OS X 10.11.3) ERROR

Error: XHR error (404 Not Found) loading http://localhost:9876/ng2-material/all

 at error (/../node_modules/systemjs/dist/system.src.js:1026:16)

 at XMLHttpRequest.xhr.onreadystatechange (/../node_modules/systemjs/dist/system.src.js:1047:13)
...
...
13 04 2016 14:55:37.058:WARN [web-server]: 404: /ng2-material/all

```
What am I missing?

**Comment by axal90** [comment]
```
System.config({
        defaultJSExtensions: true,
        typescriptOptions: { emitDecoratorMetadata: true },
        packages: {
            'node_modules/ng2-material': {
                format: 'cjs',
                defaultExtension: 'js'
            }
        },
        paths: {
            'ng2-material/all': 'node_modules/ng2-material/all'
        }
    });
```
This is my system js config, hope adding thew path helps.

**Comment by JDillon522** [comment]
Yeah, thats more or less exactly what we had to do. Thanks

**Comment by yahyaKacem** [comment]
I still can't get this to work when I `import { MATERIAL_DIRECTIVES } from 'ng2-material';` the build pass but I get `zone.js:101 GET http://dev.card.org:3000/vendor/ng2-material 404 (Not Found)` and when I add the all at the end like this: `import { MATERIAL_DIRECTIVES } from 'ng2-material/all';` the build complains about `Cannot find module 'ng2-material/all'.`
this is my system config file:

```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  'ng2-material': 'vendor/ng2-material'
};

/** User packages configuration. */
const packages: any = {
  'node_modules/ng2-material': {
      format: 'cjs',
      defaultExtension: 'js'
  }
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  'app/+login',
  'app/+download',
  'app/+dashboard',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });

```

and I added this line `'ng2-material/**/*.js',` to the `angular-cli-build.js` file.
it apears that the all.js file is not there, also there's no all.ts file.
what I'm doing wrong here, also I found this #139 and #170 which may be related to this too.

**Comment by yahyaKacem** [comment]
by the way I updated to the latest v0.4.0 of ng2-material, and downgrading to 0.3.8 didn't fix the problem except the all.js file now exist but the browser still give me this error: `zone.js:101 GET http://dev.card.org:3000/vendor/ng2-material/all 404 (Not Found)`

**Comment by kashyapmukkamala** [comment]
@yahyaKacem were you able to fix this?

**Comment by yahyaKacem** [comment]
@kashyapmukkamala sorry, not using this anymore, I'm using the official [angular/material2](github.com/angular/material2).

**Comment by kapoorruchi** [comment]
I'm facing issues running tests with angular2 seed(https://github.com/mgechev/angular-seed) karma. I'm getting below issue.
'START:
09 11 2016 12:31:12.195:WARN [web-server]: 404: /base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
Chrome 54.0.2840 (Windows 7 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:304:33)
        Error loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js as "angular2localization" from http://localhost:9876/base/dist/dev/app/app.component.js ' 
Below are my thoughts:
1. May be this issue is with the angular2localization library integration with angular2 seed.
2. Or currently I'm using, https://github.com/mgechev/angular-seed . Can this issue be due to karma version?
"name": "angular2-seed",
"version": "0.0.0"
I need an urgent help on this, it would lead to delay in my project delivery. 
Please help.
