### ISSUE TITLE
switch does not set the switch-state

### ISSUE THREAD

**Issue by mwiesmueller** [justindujardin/ng2-material#169]
When i implementate the component "md-switch" in my project, this element does not output the state of the switch.

I have compared this to the checkbox. On checkbox the state is set over "[(checked)]". On activate the checkbox the state is set as boolean in my databinding-object.

When i use the same with md-switch the state will not be change in my databinding object. Where is my error?

**Comment by justindujardin** [comment]
The md-switch component was recently removed in favor of the `@angular/material/slide-toggle` component.  

Please see more about it here: https://github.com/angular/material2/tree/master/src/lib/slide-toggle
