### ISSUE TITLE
indeterminate state's missing from checkbox

### ISSUE THREAD

**Issue by yahyaKacem** [justindujardin/ng2-material#171]
based on this [example](https://material.angularjs.org/latest/demo/checkbox) from angularjs material 1 we can put the checkbox in an indeterminate state, this is not possible as far as I know with ng2material now.

**Comment by justindujardin** [comment]
The checkbox component has been replaced with the [Material2 checkbox](https://github.com/angular/material2/tree/master/src/components/checkbox) component as of version `0.4.1`.  The material2 checkbox supports indeterminate state, please see the latest demos.
