### ISSUE TITLE
Webpack documentation

### ISSUE THREAD

**Issue by zigzag95** [justindujardin/ng2-material#175]
Hello,
I need to integrate ng2-material in my webpack project.
To make it work, I import components froml source directory :
`import {MATERIAL_DIRECTIVES} from 'ng2-material/source/all';`

when I do `import {MATERIAL_DIRECTIVES} from 'ng2-material/all';`
I get typings errors

Is there any doc explaining how to do the integration.

Thanks

**Comment by MurhafSousli** [comment]
@zigzag95 if you are using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), then its pretty simple:

Go to `src/platform/browser` directory and modify [providers.ts](https://github.com/AngularClass/angular2-webpack-starter/compare/master...MurhafSousli:patch-1) and  [directives.ts](https://github.com/AngularClass/angular2-webpack-starter/compare/master...MurhafSousli:patch-2)

**Comment by zigzag95** [comment]
Hello this is not using ng2-material. And I don't want import from src

**Comment by Zuzon** [comment]
Can you provide what errors you got? Because I use ng2-material in webpack project without any problems.

**Comment by axal90** [comment]
`WARNING in ./~/ng2-material/core/util/animate.js
Cannot find source file 'ng2-material//core/util/animate.ts': Error: Cannot resolve 'file' or 'directory' ./ng2-material//core/util/animate.ts in E:\node\msls webpack\node_modules\ng2-material\core\util
`

seems like the msource maps in ng2-material either points too the wrong place or require some configuration to work properly.

**Comment by axal90** [comment]
This seems to be a problem with the npm package.
When I build ng2-material the *.js.map files poit to the correct source *.ts file.

@justindujardin Are you using other build scripts for the npm package?

**Comment by Zuzon** [comment]
`{
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          // these packages have problems with their sourcemaps
          helpers.root('node_modules/ng2-material')
        ]
      }`

**Comment by justindujardin** [comment]
With package `0.4.1` using webpack becomes much easier.  Stay tuned for an example.

**Comment by justindujardin** [comment]
I added a really simple Webpack example of using ng2-material and material2: https://github.com/justindujardin/ng2-material/tree/master/modules/webpack

**Comment by robwafle** [comment]
Thanks!!!

Robert C.  Wafle
Founder, Principal Consultant
Chicago Code Monkeys
Serious Monkeys, Serious Code.
http://www.chicagocodemonkeys.com
Chicago: 312-924-2391<tel:312-924-2391>
Toll Free: 877-500-8575<tel:877-500-8575>
