### ISSUE TITLE
How to use <md-tabs> with routeLink?

### ISSUE THREAD

**Issue by tarlepp** [justindujardin/ng2-material#18]
I was thinking to use ```<md-tabs>``` as subnavigation on my app. And for that I need to tabs to change route, any ideas if this is possible?

**Comment by justindujardin** [comment]
Thanks for asking. I wondered about this when I did an integration with the angular2-seed project. I'll figure it out and put an example together. Stay tuned.

**Comment by DennisRoam** [comment]
@tarlepp could you not just do a menubar with a router outlet? I guess something for the indicator..

**Comment by justindujardin** [comment]
We removed the related component in favor of: https://github.com/angular/material2/tree/master/src/lib/tabs
