### ISSUE TITLE
No provider for ViewportHelper after upgrading to 0.3.6

### ISSUE THREAD

**Issue by guehmann** [justindujardin/ng2-material#183]
Now I get the folling message. Any help?? With 0.3.4 everything is ok.

![image](https://cloud.githubusercontent.com/assets/8971747/14615953/7641fe18-05a8-11e6-8773-681656296fc8.png)

**Comment by guehmann** [comment]
Sorry, only posting the half, I was using SidebarNavigation and getting this error. My .ts file is like this:
![image](https://cloud.githubusercontent.com/assets/8971747/14616358/66057104-05aa-11e6-8137-12d7e1d7e0cd.png)

**Comment by axal90** [comment]
In your supplied code you dont include ther providers. 
`import {MATERIAL_BROWSER_PROVIDERS} from "ng2-material/all";
bootstrap(App, [MATERIAL_BROWSER_PROVIDERS]);`

**Comment by guehmann** [comment]
Thank you,
this was the problem, now it's working with 0.3.6!!!
