### ISSUE TITLE
templateUrl in MdDialog

### ISSUE THREAD

**Issue by guehmann** [justindujardin/ng2-material#184]
Is there any way to use an external .html for the content of a .textContent in a MdDialog?
Has anyone some solutions in this case? Thanks.

**Comment by viirtus** [comment]
I suppose that is impossible now.
But you can extend MdDialogBasic by your own class. 
For example: 
`
@Component({
    selector: 'md-dialog-basic',
    templateUrl: 'app/dialog/app.edit-name.dialog.html',
    directives: [MATERIAL_DIRECTIVES]
})
export class AppEditNameDialog extends MdDialogBasic {
    private _person:PersonInfo = {};

    constructor(public dialog:MdDialogRef) {
        super(dialog);
    }

    loadRecord(info:PersonInfo) {
        this._person = info;
    }
}
`

**Comment by guehmann** [comment]
Ok, this helps me. Thanks.
