### ISSUE TITLE
input password bug in chrome

### ISSUE THREAD

**Issue by MurhafSousli** [justindujardin/ng2-material#185]
Hi, it seems that the official material2 will take ages to get released, I would like to contribute on this repo.

I found a bug with Input password in chrome

![password input](http://i.giphy.com/l3V0krBIwIY6U5Lfa.gif)

it would be great if you get `md-autofocus` directive in the next release. :)

**Comment by Gregcop1** [comment]
Hi thank you. Do you think you can push a pull request about it? You can follow those [guidelines](https://github.com/justindujardin/ng2-material/blob/master/CONTRIBUTING.md). Thank you

**Comment by trognus** [comment]
Not sure md-autofocus would be the way to fix this. This is a long-standing issue coming from with Chrome's handling of password autofills that also breaks Angular 1's material design, last I checked (there's some hacky workarounds, but I haven't found anything particularly elegant). 

If md-autofocus triggers the necessary event to detect the presence of a value in the input box then I could see it working as long as there's only one password input on the page (the vast majority, I'm sure) but it's still a bit of a hack, and not dealing with the core issue (which is that Chrome fills in the input without sending the expected event(s)).

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
