### ISSUE TITLE
md-input bug

### ISSUE THREAD

**Issue by zigzag95** [justindujardin/ng2-material#188]
![md-input-bug](https://cloud.githubusercontent.com/assets/7827225/14677646/a906bf30-0712-11e6-92cd-101d6d08cc84.gif)

**Comment by zigzag95** [comment]
This happened when quick typing

**Comment by axal90** [comment]
Looking at the code, it seems like the input element sets its own value as the input value. 
If that makes any sense....
I might be reading it wrong. But if you type  fast enough it can't keep up and will be setting its own value to a value state that is no longer valid.

I have no idea why it would be implemented like this. 
Will have to wait for the guys/gals with more knowledge to take a look at it.

**Comment by axal90** [comment]
If you can setup a plunkr to replicate the problem that would be great.

**Comment by janisr** [comment]
You can reproduce it when using two-way binding

` <input md-input [(value)]="title">`

**Comment by axal90** [comment]
Plunker reproducing bug: https://plnkr.co/edit/PfCv8fORFsqyFTeLeymI?p=preview
Mash the keyboard.

**Comment by zigzag95** [comment]
The used code is more standard u die: 

  <md-input-container class="md-block" flex-gt-sm>
                            <label>Definition</label>
                            <input md-input [(value)]="definition">
                        </md-input-container>

**Comment by zigzag95** [comment]
The used code is more standard u die :
`  <md-input-container class="md-block" flex-gt-sm>
                            <label>Definition</label>
                            <input md-input [(value)]="selectedKpi.data.definition">
                        </md-input-container>`

**Comment by justindujardin** [comment]
Fix deployed in `0.3.7` npm package, and closed with https://github.com/justindujardin/ng2-material/commit/4386d5677a04338ba00fe554864e6030bb45b85a
