### ISSUE TITLE
How to use side-nav

### ISSUE THREAD

**Issue by harshaldhake** [justindujardin/ng2-material#19]
Hi,

Can you please tell me how can i use side nav in ng2-material

**Comment by justindujardin** [comment]
@harshaldhake there is a sidenav component in development for the demo site navigation.  It is almost complete.  I will update this issue when it is available for use.

Thanks for your patience.

**Comment by harshaldhake** [comment]
Thanks buddy

**Comment by justindujardin** [comment]
@harshaldhake check out https://justindujardin.github.io/ng2-material/#/components/sidenav

v0.2.0 includes a workable sidenav.  Please close this issue if your needs are met.

**Comment by harshaldhake** [comment]
Thank you Justin very much
