### ISSUE TITLE
<i> icon button & md-toolbar

### ISSUE THREAD

**Issue by diamo1213** [justindujardin/ng2-material#192]
Hi,
icon buttons like 
`
<button md-fab class="md-mini" aria-label="Delete" (click)="deleteImg(photo)">
<i md-icon>remove</i>
</button>
`
go over toolbar when scrolling.
Screenshot:
[https://www.dropbox.com/s/sks9o9zh3mh469z/Screenshot%202016-04-22%2011.44.49.png?dl=0](https://www.dropbox.com/s/sks9o9zh3mh469z/Screenshot%202016-04-22%2011.44.49.png?dl=0)

**Comment by diamo1213** [comment]
i suppose issue is in https://github.com/justindujardin/ng2-material/blob/master/ng2-material/components/button/button.scss 
on line 235: z-index

**Comment by axal90** [comment]
Feel free to setup a pullrequest with a fix.

**Comment by axal90** [comment]
Have you tried with the toolbar from material2? the toolbar from this project has been deprecated.
I'll close this issue for now. Feel free to open it again if its still a problem.
