### ISSUE TITLE
md-input bugs even on examples page

### ISSUE THREAD

**Issue by zigzag95** [justindujardin/ng2-material#194]
![animation](https://cloud.githubusercontent.com/assets/7827225/14745121/11c43b36-08aa-11e6-80af-67de24c4daaf.gif)

**Comment by justindujardin** [comment]
Fix deployed in `0.3.7` npm package, and closed with https://github.com/justindujardin/ng2-material/commit/4386d5677a04338ba00fe554864e6030bb45b85a
