### ISSUE TITLE
Plans for remaining components (menu, Dialog etc.) ?

### ISSUE THREAD

**Issue by femski** [justindujardin/ng2-material#2]
Thank you for this effort - ng2material is really important to us. Somehow Google has dropped the ball - ng2 is now in beta yet there has been no progress on Angular Material 2.x in nine months !

Will you port rest of components like MdMenu and post samples for Dialog ? That will be great. Thanks again.

**Comment by justindujardin** [comment]
I posted examples of basic dialog usage today.  

I'm currently working on making sure that the existing components have decent testing around them, but I think that a menu will come up pretty quickly when I start adding more components.

**Comment by justindujardin** [comment]
I'm going to close this issue for now. Thanks for your support.

**Comment by vifore** [comment]
I can start my project with ng2-material. Thank you.
But I need sidenav and toast components.
I hope the remained components can be started.
