### ISSUE TITLE
button   , [hidden]="true"  not work

### ISSUE THREAD

**Issue by iloveyo123u1** [justindujardin/ng2-material#205]
```
<button md-fab class="md-mini" aria-label="delete" title="delete it" [hidden]="true" >
      <i md-icon>delete</i>
    </button>
```

**Comment by axal90** [comment]
Can you provide a bit more information on what is not wortking?

**Comment by iloveyo123u1** [comment]
not hidden

**Comment by steve-farr** [comment]
This is Angular2 behaviour and it's behaving as expected. Setting hidden to true isn't the correct way of hiding an element. See the following link for an explanation
http://angularjs.blogspot.com/2016/04/5-rookie-mistakes-to-avoid-with-angular.html

It's not an issue with this project.

**Comment by axal90** [comment]
Thanks @steve-farr for pointing that out.
I'm closing this issue.
Feel free to reopen it if toy have more to add.

**Comment by iloveyo123u1** [comment]
thanks   @steve-farr  @axal90
