### ISSUE TITLE
i am getting 'TypeError: Cannot read property 'mdChange' of undefined at MdInputContainer.ngAfterContentInit' error after you have fixed the 'fix(input): issue when typing rapidly into an input'

### ISSUE THREAD

**Issue by Muthu2020** [justindujardin/ng2-material#206]

**Comment by Muthu2020** [comment]
Currently i am using angular-beta version 16 and ng2-material version-0.2.12.
Can you please review it.

**Comment by axal90** [comment]
It does not seem like ng2-material is yet compatible with beta 16, so use beta 15 wich seems to be compattiple.
Also the version of ng2-material you are using does not have the input fix. 
Try updating to latest version (v0.3.7 as of writing).

I will close this issue for now. feel free to reopen it if this does not solve your problems.
