### ISSUE TITLE
Input loads with value 'undefined'

### ISSUE THREAD

**Issue by LuxDie** [justindujardin/ng2-material#21]
Hi. The latest changes have broken `input` components. Now when you add `<input md-input>` to a template, it will load with `undefined` as it's value.

**Comment by justindujardin** [comment]
Thanks for reporting this.  I fixed the issue and added a test.

Please try version `0.1.7` from NPM and if you still experience the issue, reopen this.

**Comment by LuxDie** [comment]
Cool thanks.
