### ISSUE TITLE
ng2-material version 0.3.7 does not support for *ngFor

### ISSUE THREAD

**Issue by balajijana** [justindujardin/ng2-material#212]
Hi,

 I have used the ng2-material version 0.3.7 and updated the angular 2 package to beta.17. When I used  *ngFor I am not able to get the items after iterating in the list-items.

 md-list-item.md-whiteframe-z2.md-margin.white-color(md-ink , *ngFor ="let item of menuItems; let index = index",[ngClass]="{'disabled':item.disable,'active pullright': navClass(item.link)}", (click)="activeTab(item)",style="width:100%")

Please let me know what is wrong in the above statement

**Comment by Gregcop1** [comment]
related to [this one](https://github.com/justindujardin/ng2-material/issues/207)
ATM, justin works on it

**Comment by balajijana** [comment]
I gone through the url:  https://github.com/justindujardin/ng2-material/issues/207 I have updated the *ngFor with 'let' keyword but i am not able to get the iterated items. Please help me to resolve it also the the form fields label are not in the proper styling

**Comment by Gregcop1** [comment]
can you post a plunkr to illustrate this please ?

**Comment by balajijana** [comment]
HI,

I have defined the following menuitems as object in my ts file:

public menuItems:Object[] = [
{text: 'Caregiver', icon: 'brightness_1', activeicon: 'panorama_fish_eye', check: false,disable: false, link: 'Caregiver'},
 {text: 'Patient', icon: 'brightness_1', activeicon: 'panorama_fish_eye', check: false, disable: true,link: 'Patient'},
  {text: 'Carecircle', icon: 'brightness_1', activeicon: 'panorama_fish_eye', check: false,disable:true,link: 'Carecircletab'}];

I am iterating this items in the jade file and taking the value:

md-list-item(md-ink , *ngFor ="let item of menuItems; let index = index")

I am not getting the value in the item if i use md-list-item. this is my issue

**Comment by Gregcop1** [comment]
first time I see angular2 with jade but ok. Pardon me to insist but it will be easier if you can reproduce you error with a plunkr so we can see errors and try to fix it together

**Comment by axal90** [comment]
ng2-material is currently not compattible with angular 2 beta-17.
se #207

**Comment by balajijana** [comment]
Hi,

Thank you for your reply.
Please let me know whether you will upgrade the ng2-material to make it compatible with the angular-2.beta.17 or for higher version or this is the major version as of now.

Thanks
Balaji

**Comment by Gregcop1** [comment]
angular2 RC0 has been released yesterday but it introduce a lot of breaking changes but after this step, everything should be more stable than the last month and it should be easier to maintain

**Comment by justindujardin** [comment]
The 0.3.8 build locks the angular version to beta 14, which would prevent this problem from happening until . This will be resolved with #217
