### ISSUE TITLE
md-button loses content when ngClass is applied

### ISSUE THREAD

**Issue by tothedur** [justindujardin/ng2-material#213]
After updating to Angular beta-17 and ng-material to 0.3.7 I found that a button lost it's content.  A simple version is:

`<button md-button [ngClass]="{'md-warn':bWarn}">Label</button>`

This worked in previous versions of angular (beta-14) and ng-material (not sure exact version, but last updated about a month ago).  With the updated versions I found that the content (e.g. "Label") is missing, but only when both ngClass and md-button are applied.  The content shows fine if either one is there without the other.  I went through the md-button component code, but I don't see anything that could cause this, but I wanted to check before pursuing review in angular.

**Comment by axal90** [comment]
ng-material is currently not compattible with angular 2 beta-17.
se #207

**Comment by justindujardin** [comment]
Package `0.4.1` supports the latest angular2 builds. Closing this issue.
