### ISSUE TITLE
Side

### ISSUE THREAD

**Issue by mprinc** [justindujardin/ng2-material#215]
After uprgrading to version `0.3.8` our system broke. Apparently Sidenav and Toolbar are broken with errors like:

```
No provider for ViewportHelper! (MdSidenav -> ViewportHelper)
```

We have checked [https://justindujardin.github.io/ng2-material/#/components/sidenav](https://justindujardin.github.io/ng2-material/#/components/sidenav) and [https://justindujardin.github.io/ng2-material/#/components/toolbar](https://justindujardin.github.io/ng2-material/#/components/toolbar) but even with original examples, the code breaks.

After that we tried to add aditional providers to our code
```js
import {MdBackdrop} from "ng2-material/components/backdrop/backdrop";
import {MATERIAL_DIRECTIVES, Media, SidenavService, MdToolbar} from "ng2-material/all";

// ...

    providers: [
        MdBackdrop,
        MdToolbar,
        SidenavService,
        ROUTER_PROVIDERS
    ],
```

but still problem ?!  :(

**Comment by axal90** [comment]
Try this:
```
import {bootstrap} from 'angular2/platform/browser';
import {MATERIAL_BROWSER_PROVIDERS} from "ng2-material/all";

import {App} from './app/app.component';

bootstrap(App, [
    MATERIAL_BROWSER_PROVIDERS,
]);
```

**Comment by justindujardin** [comment]
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.

**Comment by mprinc** [comment]
Sorry, in the meantime I had wedding :) back to business.

Correct, now did migrated to new version and integrated official angular2-material components and now everythings seems fine. Thanks.

We did noticed that now official sidenav component doesn't allow possibility to have to sidenavs that are both on the left side, this used to work with ng2-material/angular1 implementation. Any clue about that?
