### ISSUE TITLE
Input validation error messages are NOT automatically read

### ISSUE THREAD

**Issue by l1cmj0b** [justindujardin/ng2-material#222]
Validation messages are displayed but not read by screen reader when tabbing out of a field with a validation error on the "Nuclear Missile" form https://justindujardin.github.io/ng2-material/#/components/input.  

The 1.x version https://material.angularjs.org/latest/demo/input correctly reads the message correctly.

I am using JAWS 17 on IE11.

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.
