### ISSUE TITLE
Placeholder does not show on md-input

### ISSUE THREAD

**Issue by aviramga** [justindujardin/ng2-material#224]
Hi,

I noticed that when using md-input and trying to set the placeholder attribute using a non static string it will not show the placeholder (it will be missing from the input).

Examples:
`<input md-input flex [(ngModel)]="searchString" [placeholder]="placeholderParam" >` //Doesn't work

`<input md-input flex [(ngModel)]="searchString" placeholder="{{placeholderParam}}" >` //Doesn't work

`<input md-input flex [(ngModel)]="searchString" placeholder="some random text" >` //Works

Please look into this.

Thanks!

**Comment by justindujardin** [comment]
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of `0.4.1`.  Closing this issue.
