### ISSUE TITLE
md-dialog: when pressing enter the dialog opens again everytime

### ISSUE THREAD

**Issue by Nightapes** [justindujardin/ng2-material#226]
Hi,

I noticed when pressing enter, while a dialog is open, a new dialog is opened again.
Works only when the dialog does not have focus. 

**Works also in the demo:** 
https://justindujardin.github.io/ng2-material/#/components/dialog

**Workaround**: 
Check if the dialog is already open

**Comment by justindujardin** [comment]
The old dialog component has been replaced with `0.4.1` package.  Please open a new issue if the new component has the same problem.
