### ISSUE TITLE
Cannot implement ng2-material in my app

### ISSUE THREAD

**Issue by guehmann** [justindujardin/ng2-material#23]
Hi,

first of all. this is a very good material framework. This is not a bug report, but i need some help.
I think i implement the systems.js not correct, but i don't know why.

I hope you can help me.

I implement angular2 with typescript and system.js like this...

--> (index.html)
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="favicon.png">
    <link href="css/mdl/font.css" rel="stylesheet" />
    <link href="css/mdl/ng2-material.css" rel="stylesheet" />
    <link href="css/fonts.css" rel="stylesheet" />
    <link href="css/custom/esuite.css" rel="stylesheet" />
    <link href="css/dx/dx.common.css" rel="stylesheet" />
    <link href="css/dx/dx.light.css" rel="stylesheet" />
    <title>Econfence ESuite 2016</title>
    <script src="lib/es6-shim.min.js"></script>
    <script src="lib/system.js"></script>
    <script src="lib/typescript.js"></script>
    <script src="lib/rx.min.js"></script>
    <script src="lib/angular2-polyfills.min.js"></script>
    <script src="lib/router.dev.js"></script>
    <script src="lib/angular2.dev.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('app/boot')
            .catch(console.error.bind(console));
    </script>
</head>
<body>
    <eportal><div>Bitte warten Sie, während die Anwendung geladen wird...</div></eportal>
    <script src="lib/ng2-material.min.js"></script>
    <script src="lib/jquery.min.js"></script>
    <script src="lib/globalize.js"></script>
    <script src="lib/dx.all.js"></script>
</body>
</html>
<--

--> (config.js)
System.config({
    transpiler: 'typescript',
    typescriptOptions: {
        emitDecoratorMetadata: true
    },
    packages: {
        'app': {
            defaultExtension: 'ts'
        }
    }
});
<--

<--home.ts>
import {Component, View}    from 'angular2/core';
import {MATERIAL_DIRECTIVES, MATERIAL_PROVIDERS} from 'ng2-material/all';

@Component({
    selector: 'home'
})
@View({
    templateUrl: 'app/components/home/home.html',
    directives: [MATERIAL_DIRECTIVES]
})
export class HomeComponent {
}
<---->

The home.ts resolves quite good, but when i compile/transpile a get the following chrome error in the development tools:

-->

I hope you can help me an many thanks in advance,
Best regards, Jens.

p.s.:
Using Visual Studio 2015. Is there a parameter for searching typescript description files (all.d.ts) ?

Thanks again.

**Comment by jaroslavrehorka** [comment]
You forgot to include the error =)

**Comment by guehmann** [comment]
Yes sure. Sorry. Here comes the error

![image](https://cloud.githubusercontent.com/assets/8971747/12419896/3fd0e172-beb9-11e5-99ac-fb243653c1d9.png)

**Comment by jaroslavrehorka** [comment]
post your whole config.js please

**Comment by guehmann** [comment]
Here is the complete config.js
----------------------------
System.config({
    transpiler: 'typescript',
    typescriptOptions: {
        emitDecoratorMetadata: true
    },
    packages: {
        'app': {
            defaultExtension: 'ts'
        }
    }
});
----------------------------

**Comment by jaroslavrehorka** [comment]
ok, how did you install ng2-material? through jspm? Because you are missing mapping in your config.js

Try to install it with this command - `jspm install npm:ng2-material` it should add correct mapping to config.js

**Comment by guehmann** [comment]
Thank you. This worked fine now. I didn't know exactly about the system.js and the mappings in the config.js also about installing with jspm.
Now i'm informed. Thank you very much again. You saved my project.

**Comment by jaroslavrehorka** [comment]
no problem, I'm glad it is working now
