### ISSUE TITLE
Open Dialog automatically ?

### ISSUE THREAD

**Issue by LiTiang** [justindujardin/ng2-material#238]
before **ng2-material** upgrade to **rc**, 
i can open **Dialog** without click any button first, see below
```javascript
	private _showConfirm() {
		let config = new MdDialogConfig()
			.textContent('body')
			.clickOutsideToClose(false)
			.ok("ok")
			.cancel('cancel');
```
```javascript
		this.dialog.open(MdDialogBasic, this.element, config)
			.then((ref: MdDialogRef) => {
				ref.whenClosed.then((result) => {
					if (result) { // ok
						this._showAlarm = false;
					}
					else { // cancel
						// not yet
					}
				})
			});
	};
```

when u execute method `_showConfirm`, the **Dialog** will open automatically ( u can see there're `this.dialog.open()` ), but i can find out how to such thing in this version ... 

did u still provide this functionality ??????

THX

**Comment by LiTiang** [comment]
sorry, use `@ViewChild` & `ngAfterViewInit()` can achieve what i want

**Comment by vincentpalita** [comment]
@LiTiang : could you please provide the code you wrote to do so with @ViewChild ?

Thanks in advance!

**Comment by askaFed** [comment]
@vincentpalita 
Add this to your component
`  @ViewChild("el") el: ElementRef ;`
`  constructor(private _eref: ElementRef, private rd: Renderer ) {  }`
  `ngAfterViewInit() {
    this.rd.invokeElementMethod(this.el._elementRef.nativeElement,'click');
  } `

and reference variable to dialog button
`    <button md-raised-button class="md-primary" (click)="alert.show()" flex="auto" #el style="display: none">
             Alert Dialog
       </button>`

**Comment by vincentpalita** [comment]
@askaFed thanks but got it solved since :D

**Comment by askaFed** [comment]
@vincentpalita 
sorry did not pay attention to the date
