### ISSUE TITLE
Typescript is not able to resolve import statement.

### ISSUE THREAD

**Issue by nawalgupta** [justindujardin/ng2-material#239]
Typescript is not able to resolve import statement.
import {MATERIAL_DIRECTIVES} from 'ng2-material/all'; is not working.

[default] C:/ng2/v/app/src/app/auth/signup.ts:5:35
    Cannot find module 'ng2-material/all'.
[default] C:/ng2/v/app/src/app/auth/signup.ts:5:35
    Cannot find module 'ng2-material/all'.

I am already installed the required components using npm install. It is compatible with latest angular version?

**Comment by robwafle** [comment]
Hi Nawalgupta:

I’ve been using :

import {MATERIAL_DIRECTIVES} from 'ng2-material/src';

not sure if that is intended but it works for me at the moment.

Thx

Rob

**Comment by nawalgupta** [comment]
Thanks. 
I was trying with "all" as mentioned in doc. I will try and confirm.

**Comment by nawalgupta** [comment]
import {MATERIAL_DIRECTIVES} from 'ng2-material'; is working.

The document @ https://justindujardin.github.io/ng2-material/ is broken.
