### ISSUE TITLE
problems with typescript - ts-loader + webpack 

### ISSUE THREAD

**Issue by vladimir-ivanov** [justindujardin/ng2-material#240]
ERROR in \node_modules\@angular2-material\core\gestures\MdGestureConfig.d.ts
(4,40): error TS2304: Cannot find name 'HammerManager'.

ERROR in \node_modules\@angular2-material\core\overlay\position\global-position-strategy.d.ts
(6,22): error TS2420: Class 'GlobalPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'GlobalPositionStrategy'.

ERROR in \node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(3,31): error TS2306: File '/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

ERROR in \node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(4,10): error TS2305: Module '"/node_modules/@angular2-material/core/overlay/position/connected-position"' has no exported member 'ConnectionPair'.

ERROR in \node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(12,22): error TS2420: Class 'ConnectedPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'ConnectedPositionStrategy'.

ERROR in \node_modules\@angular2-material\core\overlay\position\overlay-position-builder.d.ts
(1,31): error TS2306: File '/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

ERROR in \node_modules\@angular2-material\core\overlay\overlay.d.ts
(5,31): error TS2306: File '/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

Tried to exlude it in tsconig.json, but no luck

**Comment by Uter1007** [comment]
How did you solved the problem ? Got the same issue...

**Comment by vladimir-ivanov** [comment]
added all files to vendors.ts to compile 
https://github.com/vladimir-ivanov/ng2-material-webpack-example/blob/master/src/vendors.ts
also make sure you have updated version of npm - should be able to support scoped npm packages (and if you are using Nexus - requires at least version 3)
https://docs.npmjs.com/misc/scope

**Comment by ollwenjones** [comment]
I got those same issues with material 2 alpha 5. Interesting.

**Comment by Uter1007** [comment]
`ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\position\global-position-strategy.d.ts
(6,22): error TS2420: Class 'GlobalPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'GlobalPositionStrategy'.

ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(3,31): error TS2306: File 'C:/src/cleanSumo/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(4,10): error TS2305: Module '"C:/src/cleanSumo/node_modules/@angular2-material/core/overlay/position/connected-position"' has no exported member 'ConnectionPair'.

ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(12,22): error TS2420: Class 'ConnectedPositionStrategy' incorrectly implements interface 'PositionStrategy'.
  Property 'apply' is missing in type 'ConnectedPositionStrategy'.

ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\position\overlay-position-builder.d.ts
(1,31): error TS2306: File 'C:/src/cleanSumo/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.

ERROR in C:\src\cleanSumo\node_modules\@angular2-material\core\overlay\overlay.d.ts
(5,31): error TS2306: File 'C:/src/cleanSumo/node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts' is not a module.`

**Comment by Uter1007** [comment]
My tsconfig:

`{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir":"../dist/public",
    "rootDir": ".",
    "moduleResolution": "node",
    "noEmitHelpers": true,
    "noLib": false
  },
  "exclude": [
    "../node_modules",
    "../dist",
    "typings/index.d.ts",
    "typings/modules",
    "../src"
//    "../node_modules/@angular2-material/core/overlay/position/overlay-position-builder.d.ts",
//    "../node_modules/@angular2-material/core/overlay/position/global-position-strategy.d.ts",
//    "../node_modules/@angular2-material/core/overlay/position/position-strategy.d.ts",
//    "../node_modules/@angular2-material/core/overlay/position/connected-position-strategy.d.ts",
//    "../node_modules/@angular2-material/core/overlay/position/relative-position-strategy.d.ts",
//    "../node_modules/@angular2-material/core/overlay/position/viewport-ruler.d.ts",
//    "../node_modules/@angular2-material/core/overlay/overlay.d.ts"
  ]
}
`
