### ISSUE TITLE
Webstorm logo link is bad in readme.md

### ISSUE THREAD

**Issue by axal90** [justindujardin/ng2-material#243]
If anybody wanna fix it go ahead.
Otherwise I'll do it when I get around to it.
@justindujardin

**Comment by axal90** [comment]
at least it does not display properly on github for me.

**Comment by justindujardin** [comment]
Fixed with: https://github.com/justindujardin/ng2-material/commit/9d30af59dcfbf2405c86bee1948a095d54454e30
