### ISSUE TITLE
Cannot find name 'HammerManager'.

### ISSUE THREAD

**Issue by gtame** [justindujardin/ng2-material#244]
I have followed the guide steps "Installing from NPM". 

But have some  errors when created the bundle. .. /@angular2-material/core/gestures/MdGestureConfig.d.ts(4,40): error TS2304: Cannot find name 'HammerManager'.

Why?

**Comment by gtame** [comment]
+Info: I am using angular2-seed project.

**Comment by ollwenjones** [comment]
@gtame I got several errors like that running webpack yesterday. It was due to the fact that npm had installed @angular2-material alpha.5 instead of alpha.4 - I don't know what was wrong with that dependency, but I had 8 or so errors in angular2-material/core, and 'HammerManager' was one of them. I asked them a question on gitter, but probably should have opened an issue.

**Comment by gtame** [comment]
@ollwenjones , 
You have reason, I did the downgrade to alpha.4 and works!
Thanks for you help. :+1:

**Comment by Gregcop1** [comment]
There's a PR which fix it

**Comment by oksurf** [comment]
When will this get fixed? 
(using webpack and keep getting  Cannot find name 'HammerManager')
I would like to try alpha 5+ to see if navbars finally work...

**Comment by leocaseiro** [comment]
Same bug with `ng2-material@0.6.1`

**Comment by leocaseiro** [comment]
I fixed following these steps:

Install hammerjs via npm:
```bash
npm install --save hammerjs
```

Install typings for hammerjs:
```
typings install --global dt~hammerjs
```

Import hammerjs on my `vendors.ts`:
```typescript
import 'hammerjs';
```

Done!

**Comment by pramttl** [comment]
I am getting the same error after updating to angular-cli@webpack from the previous SystemJS based angular-cli.

**Comment by pramttl** [comment]
@leocaseiro What is the `vendor.js` file that you are referring to? I don't have this file in my source tree. I am using angular-cli@webpack.

**Comment by leocaseiro** [comment]
Hi @pramttl, I've tried without the third step and worked it fine for me.

You won't need to import hammerjs.

**Comment by pramttl** [comment]
Looks like a better solution than using `typings` which will be deprecated [Typescript 2.0 onwards](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) is to use the npm type defintion packages provided by the npm org `@types`. In short, the following 2 steps solved my problem:

1. 
`npm install @types/hammerjs --save-dev`

2. Open **src/tsconfig.json** file and add `hammerjs` to types:

```
"types": [
  "jasmine",
  "hammerjs"
]
```

**Comment by c43** [comment]
Followed @pramttl's solution, but it didn't clear the 3 or 4 'cannot find' warnings.
I had to also add the statement
`import 'hammerjs';` in main.ts in my angular-cli build
Solution supplied here http://stackoverflow.com/a/39094250/4905938

**Comment by elSteeze** [comment]
I ran into the same issue. Simply added "import 'hammerjs'; to my main.ts file and compiled fine
