### ISSUE TITLE
Click event is being called twice on a selectable data-table when clicking checkbox

### ISSUE THREAD

**Issue by p3140** [justindujardin/ng2-material#248]
When i click on any part of the tr it works ok, but when checkbox is clicked, the code below is executed  two times:
<pre>
<b>component: <i>users-list.ts</i></b>
[...]
 change(data: ITableSelectionChange) {
    console.log(data);
    let names = [];
    this.materials.forEach((mat: any) => {
      if (data.values.indexOf(mat.id) !== -1) {
        names.push(mat.name);
      }
    });
    this.selection = names.join(', ');
    this.count = names.length;
  }
[...]
</pre>
Causing the following result in chrome:
<img src="http://65.media.tumblr.com/1d964a080cffe2eb885febb7a9f243b8/tumblr_o823dyJ73b1vwrn0xo1_1280.png">

but the expected behavior is:
<img src="https://67.media.tumblr.com/544968d0ac29f31e142a79c273898f7d/tumblr_o823ilcRbT1vwrn0xo1_1280.png">

So i suspect that maybe is a problem related with event propagation between checbox and tr, or i am making a mistake that im not seeing because it seems to work fine in documentation's site.

**Comment by axal90** [comment]
I remeber reading somewhere that angular2s changedetection is run twice when not in production mode. Didnt look into your problem specificly but it might be related.

**Comment by p3140** [comment]
Thanks axal90, but I I think if this were a problem related to changedetection , then it should happen when tr is clicked , but only occurs when the checkbox is clicked. Personally I think it is because clicking the checkbox also means clicking the tr (event propagation) because the checkbox is within the tr.
So in an old school way we used to do something like this:
<pre>
$( "md-checkbox" ).click(function( event ) {
  event.stopPropagation();
  // Do something
});
</pre>

**Comment by p3140** [comment]
[here is the code](https://github.com/p3140/angular2-meteor-starter-kit/blob/master/client/imports/admin-panel/users-panel/users-list/users-list.ts#L40)

**Comment by agungsb** [comment]
I did the workaround by adding the following function named clique() in the node_modules/ng2-material/data-table/data_table_selectable_tr.js:

`AbstractMdDataTableSelectableRow.prototype.clique = function (event) {
        event.preventDefault();
    };`

And then in both MdDataTableHeaderSelectableRow's and MdDataTableSelectableRow's template, simply add `(click)=\"clique($event)\"`

So the template should be looked like this:

`"\n        <td class=\"md-data-check-cell\">\n          <md-checkbox (click)=\"clique($event)\" #check [checked]=\"isActive\"></md-checkbox>\n        </td>\n        <ng-content></ng-content>\n    ",`

**Comment by Gregcop1** [comment]
Is this problem still exist in the last version. I don't see it in the exemple site ?

**Comment by p3140** [comment]
@agungsb your workaround worked for me too. how do we ask for a pull request or something ?

**Comment by Gregcop1** [comment]
I can do it @p3140 but what is thé version of thé plugin cuse I don't reproduce issue anymore in thé latest version

**Comment by p3140** [comment]
i'm using 0.4.1

**Comment by ollwenjones** [comment]
Pretty sure I was seeing this doing development yesterday and my branch should be up to date. - Rather, I was seeing the symptom of the checkbox not updating it if I clicked the checkbox directly.

**Comment by alalonde** [comment]
I've been seeing this issue myself, and went to create a PR for this, starting by writing some tests demonstrating the current problem.  Interestingly, I can't reproduce it in my test:
https://github.com/alalonde/ng2-material/blob/hotfix/duplicate-datatable-change-events/src/components/data-table/data_table_spec.ts#L139

**Comment by ollwenjones** [comment]
I'm wondering if it's an issue with the checkbox component itself?

**Comment by alalonde** [comment]
I think you're right: https://github.com/angular/material2/pull/672
