### ISSUE TITLE
Defining a custom color palette?

### ISSUE THREAD

**Issue by abrosey** [justindujardin/ng2-material#25]
I'm not sure if I'm missing the obvious here, but I'm looking for the implementation of the theming provider, similar to what would have been accomplished with: 

$mdThemingProvider.theme('default')
    .primaryPalette...

What is the best way to go about defining custom palettes in your implementation?

**Comment by justindujardin** [comment]
Hi @abrosey, there is no dynamic theming system for this project currently.  If you want to customize the colors, you should use the source `scss` files. Here's an example of changing the colors to brown/deep orange:

```scss
@import 'node_modules/ng2-material/source/core/style/theme-functions';
@import 'node_modules/ng2-material/source/core/style/palette';
$md-primary: md-palette($md-brown, 500, 100, 700, $md-contrast-palettes);
$md-accent: md-palette($md-deep-orange, 500, 300, 700, $md-contrast-palettes);
@import 'node_modules/ng2-material/source/all';
```

Thanks for asking, I will add this as an example to the main page.

**Comment by RicardoVaranda** [comment]
I have tried to change this but doesn't seem to be working, I changed the palette file as follows:

Original:
$md-primary: md-palette($md-indigo, 500, 100, 700, $md-contrast-palettes) !default;
$md-accent: md-palette($md-pink, 500, 300, 700, $md-contrast-palettes) !default;

After:
$md-primary: md-palette($md-blue, 500, 100, 700, $md-contrast-palettes) !default;
$md-accent: md-palette($md-red, 500, 300, 700, $md-contrast-palettes) !default;

Recompiled it with the scss compiler but no changes seemed to have been made, can you explain a bit more clearly how you can change this?

**Comment by ollwenjones** [comment]
@RicardoVaranda Are you using Webpack by chance?

**Comment by ollwenjones** [comment]
Reason I ask is last time I checked, if you import all.webpack.js seems to include the styles import - which punches any custom sass processing you do on your own.

**Comment by justindujardin** [comment]
With package `0.4.0` custom theming support has gone away.  The reason is that the library now uses the official material2 library to provide basic components, and those components do not support custom theme colors yet.  

This will be revisited as soon as material2 has a story for theming colors.
