### ISSUE TITLE
After  installing ng2Material i got this error with lite-server

### ISSUE THREAD

**Issue by achreftlili** [justindujardin/ng2-material#26]
After
npm install --save ng2-material
and without adding anything else i just run npm start ,i goyt this error with lite-server
package.json
--------------------------------------------------------------------
```json
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.13",
    "ng2-bootstrap": "^1.0.1-beta.0",
    "ng2-material": "^0.1.7",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "typescript": "1.8.0-dev.20151122",
    "systemjs": "0.19.2",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.2",
    "typescript": "^1.7.3"
  }
}
```
--------------------------------------------------------------------

![capture du 2016-01-23 21 00 59](https://cloud.githubusercontent.com/assets/4409405/12532438/9c9a85e4-c214-11e5-8d24-640b999de9a1.png)
![capture du 2016-01-23 21 01 33](https://cloud.githubusercontent.com/assets/4409405/12532439/9ca0673e-c214-11e5-86bd-b25cabd1a65a.png)
thanks.

**Comment by justindujardin** [comment]
Hi @achreftlili, I'm not sure what the issue is from what you've posted here.  NPM seems to think it's a problem with `angular2-quickstart`. Can you please ask on that repository or provide an error specific to ng2-material here?

Thanks!

**Comment by achreftlili** [comment]
thanks @justindujardin i solved this issue in my project right now after adding 
    "es6-module-loader": "^0.17.8"  "I got this dependency from your quick start project"
in the package.json file
and installed with 
npm install

**Comment by justindujardin** [comment]
Great, I'm glad it worked out!
