### ISSUE TITLE
Supporting RC2 or 3 of Angular 2? 

### ISSUE THREAD

**Issue by casserlyprogramming** [justindujardin/ng2-material#268]
Hi guys, is there any timeframe on supporting RC2 or 3 of Angular2. Currently, if I try to install on npm I get errors as I am not using RC1.

**Comment by bastienJS** [comment]
I would also appreciate an official statement about the future of ng2-material vs ng2 google material design. Both libraries have now nearly the same controls. So there will be no RC4 support?

**Comment by Gregcop1** [comment]
Hi. I'm working on PR about moving to RC3. ATM, we can't upgrade to RC4 cause we have a dependency on the official projet and they haven't upgraded yet.

About the future, the main goal of this project was and will be to provide components that respect material design recommandation and styleguide of angular2. As the official project grows (and comes with stable component) we deprecated our version of component to promote theirs. The idea is to give solutions to developers before the official team release some components... About data table, for example, it appears that it will take [some time](https://github.com/angular/material2/issues/224) :/ But finally, they work on the conception.

There's a lot of work to do about upgrading, adding new components and bug fixing and we are a small team, so if you work on some of those stuff on your side, for your project, feel free to propose us pull request. Help is always welcome
