### ISSUE TITLE
Cannot start project 

### ISSUE THREAD

**Issue by almgwary** [justindujardin/ng2-material#273]
cannot start project with` npm start` or `grunt serve`

**Comment by Gregcop1** [comment]
This PR #263 concerns you. It allow you to launch `grunt build/serve` in the root directory of the project and in another shell, `ng serve` in the `modules/site` directory.

@ollwenjones We have to fix the `readme` and fix the `package.json` to fit this new process

**Comment by MohibWasay** [comment]
Thanks man. Sorry I am new to angular-cli

**Comment by Gregcop1** [comment]
No problem. We have some work to do to simplify this process
