### ISSUE TITLE
How is a tab disabled

### ISSUE THREAD

**Issue by technoSpino** [justindujardin/ng2-material#28]
I tried 
``` html
<template md-tab label="two" disabled="true">
```
However it seemed to not be disable in my [plunkr](http://plnkr.co/edit/WTE8Fm4y9Z3njE3PHazs?p=preview).

**Comment by DennisRoam** [comment]
hey technoSpino, I don't think he's implemented the disabled attribute yet...

**Comment by DennisSmolek** [comment]
Hey @technoSpino, I started working on this after commenting and made my own tabs component. It's not perfect but it does support the disabled flag( just add disabled not disabled="true")

Here's a link to the Plunker: http://plnkr.co/edit/G1f2kIEpxNzWiMhcXXP4?p=preview

**Comment by justindujardin** [comment]
We removed the related component in favor of using: https://github.com/angular/material2/tree/master/src/lib/tabs
