### ISSUE TITLE
Angular rc.4 Cannot find module ng2-material

### ISSUE THREAD

**Issue by ebenmoha** [justindujardin/ng2-material#284]
Hello, 

I am trying to upgrade my angular2 app to the latest rc.4 version, so I updated my package.json file to include the branch feature/angular_rc4 like this:

`    "ng2-material": "git://github.com/justindujardin/ng2-material.git#feature/angular_rc4",`

It added the ng2-material dependency in my node_modules folder, but the sources was not built, so I ran a npm install and tsc inside of that folder in order to build the sources. I also updated the systemjs.config to tell systemjs to get the library from the dist folder like that:

In the map object :
       ` 'ng2-material':               'node_modules/ng2-material/dist',`
And in the packages object:
       ` 'ng2-material':               { main: 'index.js', defaultExtension: 'js' },`

When I am running my angular2 app I am getting an error telling me that ng2-material is unknown:

error TS2307: Cannot find module 'ng2-material'

Any idea ?? Thanks

**Comment by vincentpalita** [comment]
Hey, did you try with 
`'ng2-material': 'node_modules/ng2-material',`
instead of
`'ng2-material': 'node_modules/ng2-material/dist',`

**Comment by ebenmoha** [comment]
I solved the problem with copying the dist folder content to the parent ng2-material folder + settings back the map object to `'ng2-material': 'node_modules/ng2-material',`

**Comment by hakeemoriola** [comment]
Hello @ebenmoha does that mean you have ng2-material running on angular RC4. if yes please share. I have the same issue.

**Comment by ebenmoha** [comment]
Hello, well I am not sure that ng2-material is running properly, here's what I did:

Try replacing the postinstall task in your packages.json like this:

`    "postinstall": "typings install && cd node_modules/ng2-material/ && npm install && tsc && cp -rf dist/* . && cd ../../ && node-sass --recursive --output css node_modules/ng2-material/src/ node_modules/ng2-material/public/font/"`

You should have node-sass and tsc installed globally in case you are using systemjs. After running a npm install in your root folder, you must see a css folder that contains the generated stylesheets, other way you can directly require the scss files in your components if you are using webpack. Tell me if you still encountring issues. Thanks

**Comment by james-hu** [comment]
I got this error from node-sass: no mixin named md-title\n\nBacktrace:\n\tnode_modules/ng2-material/src/core/style/typography.scss:62

Any idea?

**Comment by justindujardin** [comment]
Please try the `0.6.1` build on NPM which includes RC4 support from #279

**Comment by james-hu** [comment]
@justindujardin   It works, thanks!
