### ISSUE TITLE
Cannot resolve all parameters for 'MdMaxLengthValidato' ...

### ISSUE THREAD

**Issue by ahlee2326** [justindujardin/ng2-material#29]
Cannot resolve all parameters for 'MdMaxLengthValidator'(@Attribute(mdMaxLength)). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'MdMaxLengthValidator' is decorated with Injectable.

**Comment by jaroslavrehorka** [comment]
Could you provide some example of your code?

**Comment by ahlee2326** [comment]
Sorry, I am closing this as I have reverted the codes and not currently working on it yet.
