### ISSUE TITLE
I CAN NOT INSTALL LATEST VERSION OF  NG2-MATERIAL 

### ISSUE THREAD

**Issue by maryamsoprano** [justindujardin/ng2-material#291]
Hi,
When I tried to install ng2-material version 0.6.1 , (npm install ng2-material) I got following error:

npm ERR! ng2-material@0.6.1 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-material@0.6.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-material package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-material
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-material
npm ERR! There is likely additional logging output above.

would you please help me.

**Comment by maryamsoprano** [comment]
Hi ,

it is solved. just remove node_module folder and install all components again by npm install save.
before that I could not install npm install ng2-material.

**Comment by Gregcop1** [comment]
Ok, NPM joy ;)
