### ISSUE TITLE
chore: Update to angular-2.0.x

### ISSUE THREAD

**Issue by maxime1992** [justindujardin/ng2-material#307]
It would be nice to have an update so we can use this with angular2 modules system : 

```
@NgModule({
  declarations: [
    ...
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ...
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by elaijuh** [comment]
+1
i saw the latest rc7 commit w/o introducing module

**Comment by ollwenjones** [comment]
There's a PR #300 that was opened with the rc6 update - modules are added there, but it isn't 'finished' - waiting for more community contribution / interest. In broad terms, what's necessary to finish an upgrade of "ng2-material" writ large is

1. upgrade tests
1. upgrade demo site

If you're willing to install a locally build copy to get around these hurdles temporarily, you can [clone our fork](https://github.com/Q-Free-OpenRoads/ng2-material/tree/feature/angular_2-0-0_q-free). The build script that works is `grunt build-npm`

**Comment by maxime1992** [comment]
It might be really cool ! Is there any example within your repo where I could see how to import modules and use them ? Thanks

**Comment by elaijuh** [comment]
@maxime1992 this is what i suppose should be integrated, the package is built locally

```js
import { Ng2MaterialModule } from './vendor/ng2-material'

@NgModule({
  bootstrap: [
    // AppComponent
  ],
  declarations: [
    // AppComponent
  ],
  imports: [ Ng2MaterialModule ]
```

**Comment by elaijuh** [comment]
ops... `@angular/material` 2.0.0-alpha.9 is released, bunch of things to be changed here.

**Comment by elaijuh** [comment]
@ollwenjones , since angular 2.0 final is released and `@angular/material` has a break change, is it good to open a new branch (currently #300 rc6) to fix all issues

**Comment by ollwenjones** [comment]
@elaijuh I'll open another branch. Once again my colleague updated our fork with the _material alpha.9_ to keep our other project moving. so those changes should be included already.

**Comment by ollwenjones** [comment]
Opened another branch & PR #309

**Comment by elaijuh** [comment]
@ollwenjones if you mean #308 , then ok, i will build from the fork locally for now. and what's your ETA for merging it back to master?

**Comment by ollwenjones** [comment]
@elaijuh #308 was merged into the branch that became #309 - you should be able to pull / build from [that branch](https://github.com/justindujardin/ng2-material/tree/feature/angular_2) as well. 

Unfortunatley I don't have an ETA on this. We did what we had to get our project upgraded, but we don't have time to contribute to upgrading the tests or the example site right now. Fairly sure @justindujardin won't be making a release with broken tests/site. I created the PR hoping others who cared about this project would have time to contribute.

**Comment by elaijuh** [comment]
@ollwenjones got it thanks

**Comment by justindujardin** [comment]
Please try the beta package on npm:

```
yarn add --save ng2-material@beta
```

 or 

```
npm install --save ng2-material@beta
```

**Comment by elaijuh** [comment]
@justindujardin any branch is working on the demo site?

**Comment by justindujardin** [comment]
@elaijuh yes, I just pushed it to origin.  Please see https://github.com/justindujardin/ng2-material/issues/311 for more information
