### ISSUE TITLE
ng2-material installation failed {typings: not found}

### ISSUE THREAD

**Issue by leoX2848** [justindujardin/ng2-material#310]
Am using latest version of angular-cli and when i tried to Install the ng2-material and the material2 core libraries using the command `npm install --save ng2-material @angular2-material/core` am getting error. 

Error Message : 
`zerocool@Bit:~/workspace/workout/first-app$ sudo npm install --save ng2-material @angular2-material/core
sudo: unable to resolve host Bits

> ng2-material@0.6.1 postinstall /home/zerocool/workspace/workout/first-app/node_modules/ng2-material
> typings install

sh: 1: typings: not found
first-app@0.0.0 /home/zerocool/workspace/workout/first-app
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
`-- @angular2-material/core@2.0.0-alpha.8-2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
npm WARN grunt-sass@1.2.1 requires a peer of grunt@>=0.4.0 but none was installed.
npm WARN @angular2-material/checkbox@2.0.0-alpha.6 requires a peer of @angular2-material/core@2.0.0-alpha.6 but none was installed.
npm WARN @angular2-material/checkbox@2.0.0-alpha.6 requires a peer of @angular/forms@^0.1.0 but none was installed.
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "ng2-material" "@angular2-material/core"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-material@0.6.1 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-material@0.6.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-material package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-material
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-material
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zerocool/workspace/workout/first-app/npm-debug.log
`

**Comment by justindujardin** [comment]
Please try the beta package on npm:

```
yarn add --save ng2-material@beta
```

 or 

```
npm install --save ng2-material@beta
```

**Comment by leoX2848** [comment]
It seems the issue is fixed. But what was the actual problem that had caused the error.?

**Comment by justindujardin** [comment]
The old version used typings. If your project did not include it as a dependency, this error would happen. Typings has been removed in favor of using npm @types packages.
