### ISSUE TITLE
md-message does not appear with minLength and maxLength

### ISSUE THREAD

**Issue by ZeBigDuck** [justindujardin/ng2-material#32]
Hi all!

I just tried to make a form copying what's working on your site, but it seems that Validators.minLength and Validators.maxLength does not make  appear <div md-message="maxlength">Too long</div>

I tried with several other validators with no problems. And the Validator **is** working because I have `{{ myForm.form.valid }}` that toggles from false to true processing these constraints.

Nothing anormal in console.

But this is strange because it's working as expected on your website. Maybe it's a regression.

Thank you!

**Comment by justindujardin** [comment]
@ZeBigDuck sorry to hear that you're having issues.  Can you please provide a Plunkr example so I can debug this?
