### ISSUE TITLE
First pass at new tabs component. 

### ISSUE THREAD

**Issue by DennisSmolek** [justindujardin/ng2-material#33]
I started working on a portion of my app that needed tabs and saw there was some room for improvement and got carried away. A lot of the old stuff had artifacts from ng1 so I redid it with some help from a few ng2 articles. 

Here's a link to the gist: https://gist.github.com/DennisSmolek/c090f058a24a9739dbb0
most of it's contained in a single component file but I had to add/adjust some css so theres my SASS as well. 

The biggest thing for me was simplifying the base template code to:
```javascript
<md-tabs>
  <md-tab label="one">
    <h1>Tab One</h1>
      <p>Content</p>
  </md-tab>
  <md-tab>
      <h1>Tab Two</h1>
      <p>Content</p>
  </md-tab>
  <md-tab label="three">
      <h1>Tab Three</h1>
      <p>Content</p>
  </md-tab>
</md-tabs>
```

What it can do:

- Disabled Elements
- Selectable from using selected="2"
- be "non-selected'
- Can add/remove tabs easily
- Full width or text sized
- Align left/right and top/bottom
- Pass router links

What it still needs:
- Simple Theme Support (you can use classes and selectors but no default themes yet)
- Animations
- Pagination
- Better DOM ready strategy to calculate InkWidth

NOTE: I run in Production mode because of a glitch in the beta which I think is an issue with this too as the error fires because I update the ink position too fast but I can't figure out a better way just yet.. enabling production mode removes the error message. 

Here's a link to a plunker with some examples: http://plnkr.co/edit/G1f2kIEpxNzWiMhcXXP4?p=preview

**Comment by justindujardin** [comment]
@DennisSmolek thanks for your contributions! The behaviors you describe sound really nice, but your plunk goes to a menu component demo (did you get the wrong url?) 

I don't have a ton of time right now, maybe @jaroslavrehorka could help get you set up with the build system and create a pull request?  It's a pretty straightforward grunt setup, and it would make giving you feedback a lot easier.

I'll put together a how to document on contributing components just as soon as I'm done working on the site menu nav.

**Comment by jaroslavrehorka** [comment]
I have some free time, feel free to ask if you have any problem with setting up the build, I can also help with tests etc.. =)

**Comment by DennisSmolek** [comment]
Can you try the link again? It's going to the tab demo for me. I can fork it if needed but the link should be good. 

Yeah I didn't know how you wanted stuff submitted, PR's etc.

**Comment by jaroslavrehorka** [comment]
Link seems ok to me and it looks really good!

Best way how to submit PR is to include example (like https://justindujardin.github.io/ng2-material/#/components/tabs), I can help with that if needed =)

**Comment by justindujardin** [comment]
@jaroslavrehorka if you've got time, it would be great to have this submitted in a PR.

**Comment by justindujardin** [comment]
We removed the tabs component in favor of: https://github.com/angular/material2/tree/master/src/lib/tabs
