### ISSUE TITLE
Project Deprecation - 01/15/2017

### ISSUE THREAD

**Issue by justindujardin** [justindujardin/ng2-material#332]
It has been a fun project building and maintaining a set of components that were inspired by material design for angular2. The original aim of this project was to fill in the gap while there was no official material components implementation. 

The official project has finally released its demo site, so it's now time to scrub the internet of this project to avoid confusion. This includes the following actions:

 - remove published examples site to avoid search confusion
 - add deprecation notice to the top of the realm

Thanks for all your support, and best of luck with your angular2 apps.  Head on over to https://material.angular.io to get started.

❤️

**Comment by justindujardin** [comment]
I've made the changes outlined above.

**Comment by ollwenjones** [comment]
Thanks for the good work in here @justindujardin! I wasn't able to contribute as much to this lib as I hoped, but it did help us fill the gaps waiting for the official implementation.

Best of luck on your other ventures!

**Comment by Gregcop1** [comment]
Thx for your awesome work @justindujardin @ollwenjones 
It's been awhile since I gave some news, and I'm sorry about that. Angular releases followed a chaotic path and this project suffered a lot of those stranges decisions but all this time, this project helped a lot of people, it's a fact. So thank to all of you for the fun and for the help you gave to me.

**Comment by gorghoa** [comment]
Indeed, kudos to all contributors to this project. It a was a breeze of fresh air and consistency while beta testing angular 2 ^^ 👏 ❤️

**Comment by ollwenjones** [comment]
@Gregcop1 I learned a few valuable things from you collaborating here, from "across the pond" (as they say in the UK), so thank you. 👏
