### ISSUE TITLE
Import ng2-material to existing project

### ISSUE THREAD

**Issue by pallmallshow** [justindujardin/ng2-material#37]
Hi guys,

I'm trying to use ng2-material on a existing project, without use any angular2-seeder.
So, I have added ng2-material package by using npm : 

`npm install ng2-material`

The package was correctly download and placed at node_modules/ng2-material.

In my main.ts (here is my bootstrap function), I just import MATERIAL_PROVIDERS like this : 
```javascript
import {bootstrap} from 'angular2/platform/browser';
import {AppComponent} from './AppComponent';

import {MATERIAL_PROVIDERS} from 'ng2-material/all';

bootstrap(AppComponent, [
  MATERIAL_PROVIDERS
]);
```

After many research, I need to map the package in `System.config` (in index.html file).
I wrote this : 
```javascript
System.config({
  packages: {
    app: {
      format: 'register',
      defaultExtension: 'js'
    },
    'ng2-material': {
      format: 'register',
      defaultExtension: 'js'
    }
  },
  map: {
    'ng2-material': 'node_modules/ng2-material'
  }
});
System.import('app/main')
      .then(null, console.error.bind(console));
```

It's look ok, no 404, but I have this error : 

> Uncaught ReferenceError: require is not defined (all.ts :1)

Did you got any idea ? Maybe it's my mapping configuration ?

Thanks in advance !

**Comment by jaroslavrehorka** [comment]
Hi, your error says something about file call all.ts, can you provide us that file too so we can have a look on it?

**Comment by pallmallshow** [comment]
Thanks for your react !

The all.ts is this file : https://github.com/justindujardin/ng2-material/blob/master/ng2-material/all.ts

I search again on my side !

**Comment by jaroslavrehorka** [comment]
ah that is **all.ts** from ng2-material :laughing:.. I wonder, do you have systemjs included?

**Comment by pallmallshow** [comment]
I found the solution ! (Idiot one...)

So, in `System.config`, we dont need to set the `format : 'register'`.
Finally, it works with this : 

```javascript
System.config({
  packages: {
    app: {
      format: 'register',
      defaultExtension: 'js'
    },
    'ng2-material': {
      defaultExtension: 'js'
    }
  },
  map: {
    'ng2-material': 'node_modules/ng2-material'
  }
});
```

I think you can add it on you're website or Readme, cause certainly much people going have this error !

**Comment by jaroslavrehorka** [comment]
I'm glad you solved it! I think that you can omit format even in app package, it can be autodected (https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection)
