### ISSUE TITLE
Dynamic input fields

### ISSUE THREAD

**Issue by pallmallshow** [justindujardin/ng2-material#39]
Hi guys,

There is a problem with label animation of a input.
In fact, in my case, I made a Ajax request to get data for populate this form.

For example : 
```html
<form name="userForm">
  <div layout-gt-sm="row">
    <md-input-container class="md-block" flex-gt-sm>
      <label>Name</label>
      <input md-input [(value)]="customer.name">
    </md-input-container>
  </div>
</form>
```

```javascript
export class CustomerEditComponent{
  private customer : Customer = new Customer;

  constructor(private _CustomersService: CustomersService, private _routeParams: RouteParams){}

  ngOnInit(){
    let id = this._routeParams.get('id');
    this._CustomersService.getById(id).subscribe(res => {this.customer = res; console.log(this.customer)});
  }
}
```

(To explain, I get the 'id' given in params, and I made a request to get a JSON).

My console log is ok, but this is what I have : 
![image](https://cloud.githubusercontent.com/assets/3269166/12756055/46e43fbc-c9d2-11e5-808d-b1c3ade196c3.png)

But when I click on it : 
![image](https://cloud.githubusercontent.com/assets/3269166/12756071/5711c724-c9d2-11e5-9e6c-14166b757a0f.png)

The input value appears.

If I don't change the value, if I blur the input (click outside of him), the label returned to his place (like the first screen). But if I change the value, everything is alright !

I'm trying to make a PR ;)

EDIT: PR was made : #40

**Comment by justindujardin** [comment]
@pallmallshow This issue should be fixed in v0.2.5 which is now on NPM.  Please confirm and close.
