### ISSUE TITLE
Does not display in safari 5.1.7

### ISSUE THREAD

**Issue by mijzcx** [justindujardin/ng2-material#46]
examples does not display in safari 5.1.7

**Comment by mijzcx** [comment]
![image](https://cloud.githubusercontent.com/assets/1009279/12909861/19b89da8-cf40-11e5-9ca6-69705f20857c.png)

**Comment by jaroslavrehorka** [comment]
this version is outdated and not supported by angular - https://github.com/angular/angular/issues/6265 safari 9.0.3 runs examples without any troubles

**Comment by jaroslavrehorka** [comment]
closing
