### ISSUE TITLE
Does not display in IE 11

### ISSUE THREAD

**Issue by mijzcx** [justindujardin/ng2-material#47]
Examples does not display in IE 11.

**Comment by ollwenjones** [comment]
Hm... So there are a lot of broken things... I'd say this is an epic that should be broken down, though.

**Comment by justindujardin** [comment]
The unit tests assert that the behavior of the components should be good, but I have no idea about how they look. Can either of you attach a few screenshots and any console errors?

**Comment by mijzcx** [comment]
![image](https://cloud.githubusercontent.com/assets/1009279/12909759/726992c8-cf3f-11e5-9f75-c6ba4f32596a.png)

**Comment by mijzcx** [comment]
No error output. Only warn.

**Comment by jaroslavrehorka** [comment]
In my IE examples run but their behaviour is sometimes weird (ink-drop)
![bez nazvu](https://cloud.githubusercontent.com/assets/7473041/12910497/82e35550-cf0b-11e5-88d2-e6d3194450ce.png)

**Comment by mijzcx** [comment]
agree. some weirdness in behavior.

**Comment by ollwenjones** [comment]
I have edge as well. Things weren't showing up immediately, some things didn't show up at all (half the check-boxes). The ripple animations all started from mouse origin, but then animated off the bottom of the click target, only expanding to a circle about half its width. The lack of console errors (or unit test failures) makes me think these are primarily CSS compatibility issues.

**Comment by grebett** [comment]
Sadly, I do not have a legacy version of IE11 and some PC with Windows 7/8/10 under the hood to test it but I've tried few user tests with virtual machines. A lot of components does not display well:
+ Card with image
+ Inputs (placeholders, data checking mainly)
+ Progress-linear (Buffer and Determinate... the two others seem to be erratic)
+ Sidenav (does not work at all)

If you don't have some machine running under Windows like me, you can find the proposed by Microsoft itself [here](https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/).

**Comment by justindujardin** [comment]
Sorry to hear about the IE problems.  I do not have time to address them myself, but would welcome PRs to address them.
