### ISSUE TITLE
Example buttons does not ripple in opera

### ISSUE THREAD

**Issue by mijzcx** [justindujardin/ng2-material#49]
does not ripple in opera

**Comment by jaroslavrehorka** [comment]
what version? lastest opera runs fine =)

**Comment by mijzcx** [comment]
![image](https://cloud.githubusercontent.com/assets/1009279/12910503/3a784ab0-cf46-11e5-960f-6647bd549fda.png)

Opera 35.0 (does not ripple where icon finger is pointing). But sidebar buttons, no problem.

**Comment by jaroslavrehorka** [comment]
ok, I can confirm this issue

**Comment by justindujardin** [comment]
@jaroslavrehorka do you have interest in looking at updating the ripple effect?  It seems like my poor ink ripple implementation could be better on non-chrome browsers.

**Comment by justindujardin** [comment]
I created a single ticket to address the ink ripple animation problems, #87. Closing this as a duplicate.
