### ISSUE TITLE
"tsd install" fails during "npm install" v.0.2.2

### ISSUE THREAD

**Issue by ollwenjones** [justindujardin/ng2-material#51]
I don't know if it's because I don't have TSD installed globally, or if it's because of the occasional issue with Windows finding things in the node_modules folder, but it errors out in the `postinstall`
```console
npm ERR! zone.js@0.5.11 postinstall: `tsd install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zone.js@0.5.11 postinstall script 'tsd install'.
npm ERR! This is most likely a problem with the zone.js package
```
Also (maybe a separate issue), TSD is deprecated in favor of [Typings.](https://github.com/typings/typings) See the deprecation notice here: https://github.com/DefinitelyTyped/tsd

Typings or TSD... implementers shouldn't need to install dependencies of dependencies globally, right?

**Comment by ollwenjones** [comment]
Can I say "Nevermind"? L ooks like this is an issue with zone.js, not this project.

**Comment by justindujardin** [comment]
@ollwenjones yeah, zone had a problem with this.  It's good you opened an issue so people that run into it will find a solution.
