### ISSUE TITLE
Card title too much padding

### ISSUE THREAD

**Issue by szechyjs** [justindujardin/ng2-material#52]
Prior to the 0.2.2 release card titles worked as expected.  Now there seems to be way to much padding, which pushes the title down into the content.

![screen shot 2016-02-09 at 5 13 09 pm](https://cloud.githubusercontent.com/assets/847739/12932414/addaa886-cf50-11e5-87bc-d9bc6c626ac1.png)

````html
<md-card>
    <md-card-title>
        <md-card-title-text>
            <span class="md-headline">Hosts</span>
        </md-card-title-text>
    </md-card-title>
    <md-card-content>
        <table>
            ...
        </table>
    </md-card-content>
</md-card>
````

**Comment by justindujardin** [comment]
@szechyjs can you pinpoint the styles that are wrong or suggest a fix?

**Comment by sunshineo** [comment]
I have the same problem, but I found that if you have an extra <div>, everything works.
`
<md-card>
  <div>
    ......
  </div>
</md-card>
`

**Comment by szechyjs** [comment]
@sunshineo, that fixed the problem for me as well.

I'm still trying to pinpoint the problem in the css.

**Comment by sunshineo** [comment]
@szechyjs My understanding is that this project is temporary. Maybe not worth digging it.

**Comment by noorahmed94** [comment]
@sunshineo Works for me as well

**Comment by sunshineo** [comment]
Glad I can help

**Comment by justindujardin** [comment]
We removed the related component in favor of using: https://github.com/angular/material2/tree/master/src/lib/card
