### ISSUE TITLE
About 'System.register' using extensions

### ISSUE THREAD

**Issue by erictsangx** [justindujardin/ng2-material#53]
Hi, my tsconfig is using ``system`` modules.

I found dist/ng2-material.js is using extensions e.g. ``System.register("ng2-material/components/form/validators.ts", ["angular2/src/facade/lang.js" ...``.

But angular2 bundles do not use extensions, e.g. ``System.register("angular2/src/facade/lang", [], true, function(require, exports, module)...``

It makes ``systemjs`` cannot load the modules from angular2.

**Comment by pmneo** [comment]
Solved this issue with a little System workaround:
`                var _normalizeSync = System.normalizeSync;
                System.config( {
                    normalize: function( name, parentName ) {
                        return new Promise( function( resolve, reject ) {
                            var normalized = _normalizeSync.apply( System._loader.loaderObj, [ name, parentName ] );
                            
                            if( normalized in System.defined )
                            {
                                resolve( normalized );
                                return;
                            }
                            else
                            {
                                var chain = [];
                                
                                if( endsWith( normalized, ".ts" ) || endsWith( normalized, ".js" ) )
                                    chain.push( normalized.substr( 0, normalized.length - 3 ) )
                                else
                                {
                                    chain.push( normalized + ".js" );
                                    chain.push( normalized + ".ts" );
                                }
                                
                                for( var i=0; i<chain.length; i++ )
                                {
                                    if( chain[i] in System.defined )
                                    {
                                        resolve( chain[i] );
                                        return;
                                    }
                                }
                            }
                            
                            console.log( "can't normalize ", normalized );
                            resolve( normalized );
                            return;                            
                        } );
                        n.catch( function( err ) {
                            console.error( err );
                            reject( err );
                            
                        } );
                    }
                } );`

**Comment by Maks3w** [comment]
The following workaround is more simple:

```js
    System.config({
        packages: {
            'node_modules/ng2-material': {
                defaultExtension: 'js'
            }
        },
        paths: {
            'ng2-material/*': 'node_modules/ng2-material/*'
        }
    });
```

**Comment by justindujardin** [comment]
Closing this thanks to the workarounds.  If someone wants to look at updating the grunt `dist-bundle` task to fix this more complete, I'd welcome a PR.
