### ISSUE TITLE
NPM repo should be compiled

### ISSUE THREAD

**Issue by pjwalmsley** [justindujardin/ng2-material#54]
From what i've read it's best practice to publish your repo to NPM/Bower as JS wrapped in a module with an accompanying .d.ts file for use by the ide.  :)

Looks promising - excited to get playing with the code! :)

**Comment by justindujardin** [comment]
@pjwalmsley can you tell me more about what you expect? If you install the project using NPM, you should receive the compiled files as well as the source files in your node_modules/ng2-material folder.

**Comment by pjwalmsley** [comment]
Woops, your right... Things weren't working and I overlooked that. *facepalm* This can be closed.
