### ISSUE TITLE
Attempt to use dehydrated mdFocusChange

### ISSUE THREAD

**Issue by TylerEich** [justindujardin/ng2-material#55]
I have a page that uses `<md-input>` and autofocuses it. When the user attempts to navigate away, I display a modal dialog using `confirm()`, and the Router navigates away if the confirm dialog returns `true`.

If the input is focused at the time I attempt to navigate away, ng2-material throws an error:

> Uncaught Attempt to use a dehydrated detector: MyFormPageComponent_0 -> mdFocusChange

**Comment by justindujardin** [comment]
@TylerEich can you please provide a plunkr to demonstrate the problem?

**Comment by blyndcide** [comment]
I'm seeing this problem too.  Anytime I navigate away when md-input is in focus.  Using it like this:

`            
   <form (ngSubmit)="onSubmit()" [ngFormModel]="theForm">
            <md-input-container>
                <label>Username</label>
                <input md-input type="text" [ngFormControl]="controls.userName" />                       
            </md-input-container>
   </form>
`

**Comment by wallace41290** [comment]
I am also seeing this problem. Today I updated to angular2@2.0.0-beta.7 and ng2-material@0.2.5, or at least I am trying to. My build seems to work error free, I start up the app which goes to a very simple login page, try to log in and it all crashes and burns, here is what I see in the browser console:

`angular2.dev.js:23093 EXCEPTION: Attempt to use a dehydrated detector: e_0 -> mdFocusChange
angular2.dev.js:1206 Uncaught Attempt to use a dehydrated detector: e_0 -> mdFocusChangeExceptionHandler.call @ angular2.dev.js:1206(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635errorHandling.onError @ angular2.dev.js:13543Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558arguments.(anonymous function) @ angular2-polyfills.js:1674
angular2.dev.js:23093 EXCEPTION: RangeError: Maximum call stack size exceeded`

**Comment by justindujardin** [comment]
Thanks for the extra info, I've worked around this by changing the event emitters to be synchronous as suggested in https://github.com/angular/angular/issues/6786#issuecomment-183475058

Please try 0.2.6 (on npm now) and let me know if this doesn't solve your problems.

**Comment by sylvaindumont** [comment]
On 0.2.7, input blinks, then
EXCEPTION: Attempt to use a dehydrated detector: MyFormPageComponent_0-> valueChange

**Comment by sylvaindumont** [comment]
see this example :
![ng2-blink](https://cloud.githubusercontent.com/assets/5496488/13380638/2354f624-de48-11e5-815c-8d1b75c4f0f1.gif)

**Comment by justindujardin** [comment]
@sylvaindumont please let me know if this issue is resolve with 0.2.8.

**Comment by sylvaindumont** [comment]
@justindujardin still not work, same input blinks and error

**Comment by justindujardin** [comment]
Okay, I have asked for comment on the angular issue that this is related to.  I'll let you know what I hear back.  In the mean time could you please produce a Plunkr that shows the issue?

**Comment by sylvaindumont** [comment]
Here is the plunkr :
https://plnkr.co/edit/HDnKg96s5FeCt3rxezPm?p=preview
It doesn't happen every time, it's only happen with latency under 100ms.

Now, plunkr serve the data in 150ms, so I need to download the plnkr to have the bug.

**Comment by justindujardin** [comment]
So I'm not really sure how to fix this, and the google team has been silent on the issue for a long while.

If this problem impacts your app development, please [add a respectful comment or +1](https://github.com/angular/angular/issues/6786) to the angular issue.

**Comment by nathasm** [comment]
So I have the same issue as the gif provided by @sylvaindumont however I am not seeing any dehydration errors in my console.

**Comment by fedorinoGore** [comment]
Very similar problem on **Ionic 2**.
Having` 'Attempt to use a dehydrated detector: TextInput_0 -> focusChange'` every time when switching divs with [ngSwitch] and input has focus

```
 <ion-segment [(ngModel)]="authType">
            <ion-segment-button value="login">
                Вход
            </ion-segment-button>
            <ion-segment-button value="signup">
                Регистрация
            </ion-segment-button>
        </ion-segment>
  
```  
    <div [ngSwitch]="authType">
        <form *ngSwitchWhen="'login'" [ngFormModel]="loginForm">
            <ion-item class="traps">
                <ion-label floating>Телефон</ion-label>
                <ion-input type="tel" ngControl="username" value="{{user.username}}"></ion-input>
            </ion-item>
            <ion-item>
                <ion-label floating>Пароль</ion-label>
                <ion-input type="password" ngControl="password"></ion-input>
            </ion-item>
            <div *ngIf="password.hasError('required') && password.touched" class="error-box">* Введите пароль</div>
            <div padding>
                <button block type="button" (click)="login($event)">Войти</button>
                
            </div>
        </form>
        
        
        <form *ngSwitchWhen="'signup'" [ngFormModel]="signupForm">

            <ion-item>
                <ion-label floating>Телефон</ion-label>
                <ion-input type="tel" ngControl="username"></ion-input>
            </ion-item>

            <ion-item [class.error]="!password.valid && password.touched">
                <ion-label floating>Пароль</ion-label>
                <ion-input type="password" ngControl="password"></ion-input>
            </ion-item>
            <div *ngIf="password.hasError('required') && password.touched" class="error-box">* Введите пароль</div>
            
            <ion-item [class.error]="!password.valid && password.touched">
                <ion-label floating>Повторите пароль</ion-label>
                <ion-input type="password" ngControl="repeatPassword"></ion-input>
            </ion-item>
            <div *ngIf="signupForm.hasError('mismatchedPasswords') && repeatPassword.touched" class="error-box">* Повторный пароль не совпадает!</div>
            
            <div padding>
                <button block type="button" (click)="signup($event)" [disabled]="!signupForm.valid">Зарегистрироваться</button>
            </div>

        </form>
    </div>
```

**Comment by vishalbk** [comment]
The https://github.com/justindujardin/ng2-material/issues/89 issue exists in the examples page currently, and in the build i am working with 0.3.5. Also in the plunkr example https://plnkr.co/edit/HDnKg96s5FeCt3rxezPm?p=preview.
1. Goto https://justindujardin.github.io/ng2-material/#/components/input
2. select any input field say title.
3. Enter a bunch of characters say (alksdlmaslkdm), at random (like go crazy on your keyboard) and you'll see randomly changing letters in a loop.
4. There is now way to stop it . .nothing works, except a page refresh.

**Comment by justindujardin** [comment]
We removed the related component in favor of using: https://github.com/angular/material2/tree/master/src/lib/input
