### ISSUE TITLE
Custom Dialog

### ISSUE THREAD

**Issue by loul42** [justindujardin/ng2-material#56]
Hi 

I am trying to use custom dialog. I can't make it work.
Do you have a working example ?

MdDialog.show has been implemented?

Thank you

**Comment by justindujardin** [comment]
Custom dialogs should be fine, but there are no examples right now.

**Comment by yannvr** [comment]
You can insert custom HTML content over basic dialog configurations with https://github.com/justindujardin/ng2-material/pull/99

**Comment by loul42** [comment]
@yannvr  Thanks going to try this

**Comment by ChristianBeilschmidt** [comment]
The attempt of @yannvr does not seem to be a good solution in my opinion. One should place a component inside the dialog window, not plain HTML source. In material 1 it was a template plus a controller.

For me it seems possible to switch from the `MdDialogBasic` to a custom one. But I'm not quite sure how to deal with the dialog size. And much more important, currently it seems that I can only use primitive data types as an input (e.g. string, but not object).

We should come up with an example if this it possible. Maybe I'll try to show what I am able to do currently. But maybe others have some more insight to this.

**Comment by dweitz43** [comment]
@ChristianBeilschmidt I created a custom dialog that takes an object as input for my simple application, you can see it [here](https://github.com/dweitz43/angular2-webpack-starter/tree/dweitz/src/app/hockey). theres too much going on here and i definitely need to clean most of it up when i get some more free time away from work. 

the showGoals and showTeam functions in hockey.ts are used to create custom DialogConfigs and pop each dialog. the custom dialog config is defined in the models/ directory and extends the MdDialogConfig. the actual custom dialog components themselves are also defined in the models/ directory.

For me, this approach has functioned correctly and well enough for me to put off the necessary clean up that will inevitably need to happen very soon. 

I would love and sincerely appreciate any feedback or input anyone has on this approach. It always feels like there is a better/more elegant/more efficient approach....

**Comment by ollwenjones** [comment]
For full flexibility it should wrap/boostrap an arbitrary component, with perhaps some hooks to set dimensions.

**Comment by ollwenjones** [comment]
Maybe pass a `TemplateRef` to the dialog service in order to embed a component?

**Comment by justindujardin** [comment]
The new dialog component in `0.4.1` makes it really easy to build custom dialogs.

https://justindujardin.github.io/ng2-material/#/components/dialog

```html
<md-dialog #custom>
  <md-dialog-title>Did you like it?</md-dialog-title>
  Scott Pilgrim vs. the World
  <md-dialog-actions>
    <a md-button href="https://en.wikipedia.org/wiki/Scott_Pilgrim_vs._the_World">
      <span>What's that?</span>
    </a>
    <span flex></span>
    <button md-button (click)="custom.close(false)">
      <span>It was awesome!</span>
    </button>
    <button md-button class="md-primary" (click)="custom.close(true)">
      <span>It was trying too hard...</span>
    </button>
  </md-dialog-actions>
</md-dialog>

<button md-button (click)="custom.show()">Feedback</button>
```
