### ISSUE TITLE
The future of ng2-material

### ISSUE THREAD

**Issue by LisaTatum** [justindujardin/ng2-material#57]
Now where the folks from google started with the official material design, do you still continue developing your own solution or merge with them.

I would find it counter productive. I would appreciate a statement, because I can go only in one direction and choose my "control supplier".

**Comment by Zuzon** [comment]
I think migration to official framework would be without any big problems

**Comment by eelwayadmin** [comment]
Where is the official material design ?

**Comment by grebett** [comment]
https://github.com/angular/material2

They are at a very early stage of development for now.

**Comment by justindujardin** [comment]
@LisaTatum I will explore ways to migrate this project to the official implementation as it becomes more complete.  I added a note in the readme about it: https://github.com/justindujardin/ng2-material/commit/792e4afac1fe71ae07a596973e3a36a87b636166
