### ISSUE TITLE
great work，but  safari with problem!!

### ISSUE THREAD

**Issue by forfuns** [justindujardin/ng2-material#58]
I found the safari effect might be a problem

I just use chrome and safari ，and the demo same problem , pls fix it .

**Comment by justindujardin** [comment]
I don't understand what your problem is.  Please provide information (code examples or screenshots).

**Comment by forfuns** [comment]
@justindujardin my english no good,but you can try use `md-rasied-button` in safari,u can see the the difference between Chrome

**Comment by justindujardin** [comment]
I created a single ticket to address the ink ripple animation problems, #87. Closing this as a duplicate.
