### ISSUE TITLE
All.d.t.s contains triple slash reference: Which causes an error to be thrown by the typescript compiler

### ISSUE THREAD

**Issue by schippie** [justindujardin/ng2-material#70]
The latest version (0.2.3) contains an error within the all.d.ts file:

`ERROR in <<root>>\node_modules\ng2-material\all.d.ts
(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.`

The following file: 
https://github.com/justindujardin/ng2-material/blob/master/ng2-material/all.ts

Cannot contain this line:
`///<reference path="../node_modules/angular2/typings/browser.d.ts"/>`

**Comment by schippie** [comment]
Tried to fix it but that throws a lot more errors when i remove the line and try to do a grunt build within the fork I created. So I removed the fork.

**Comment by justindujardin** [comment]
@schippie This issue should be fixed in v0.2.5 which is now on NPM.  Please confirm and close.
