### ISSUE TITLE
issue with postinstall script

### ISSUE THREAD

**Issue by vladimir-ivanov** [justindujardin/ng2-material#74]
21-Feb-2016 18:06:56	npm ERR! ng2-material@0.2.3 postinstall: `typings install`
21-Feb-2016 18:06:56	npm ERR! Exit status 1
21-Feb-2016 18:06:56	npm ERR! 
21-Feb-2016 18:06:56	npm ERR! Failed at the ng2-material@0.2.3 postinstall script 'typings install'.
21-Feb-2016 18:06:56	npm ERR! This is most likely a problem with the ng2-material package,
21-Feb-2016 18:06:56	npm ERR! not with npm itself.
21-Feb-2016 18:06:56	npm ERR! Tell the author that this fails on your system:
21-Feb-2016 18:06:56	npm ERR!     typings install
21-Feb-2016 18:06:56	npm ERR! You can get their info via:
21-Feb-2016 18:06:56	npm ERR!     npm owner ls ng2-material
21-Feb-2016 18:06:56	npm ERR! There is likely additional logging output above.

**Comment by agustin107** [comment]
I have the same problem, when i want to deploy app on Heroku.

**Comment by vladimir-ivanov** [comment]
seems it needs typings.json to exist in the root of your project 
add typings in package.json, then do
`
typings init
`

That creates the file and gets rid of the issue above

**Comment by agustin107** [comment]
Where i have add the `typings init`? Thanks!

**Comment by vladimir-ivanov** [comment]
in the root of your project - add typings to your package.json
e.g. 
    "typings": "^0.6.8",

then run npm install (or alternatively npm install --save-dev typings)

then run typings init from the root of your project again

**Comment by agustin107** [comment]
I still have the same problem, when i do deploy on Heroku ..

`sh: 1: typings: not found`

I add typings as dev dependencies, but i think that require as global module..

**Comment by vladimir-ivanov** [comment]
that resolved it for me on the build server :-(

**Comment by justindujardin** [comment]
Please try the 0.2.4 build that I just released and re-open this issue if it's still not working for you.

**Comment by vladimir-ivanov** [comment]
guessing that postinstall script is redundant (causing trouble when the typings.json file is not empty behind a corporate proxy - fails)

**Comment by vladimir-ivanov** [comment]
the issue with ///<reference> at the top of all.d.ts is more critical :-)

**Comment by justindujardin** [comment]
@vladimir-ivanov yeah I see the /// problem, but that's a different issue (and it's still open.)

Are you still having trouble with the postinstall script when you install 0.2.4?

**Comment by vladimir-ivanov** [comment]
did not try 0.2.4 - 0.2.3 finds typings command - ./node_modules/.bin/typings install as in 0.2.4 will lead to the same result for me - our build server does not have access to the Internet, so it fails regardless. 
As soon as I add any ambient typings in our typings.json file (tries to access github, which is an external website)

**Comment by justindujardin** [comment]
@vladimir-ivanov I see, that makes sense.  I will add the typings folder to the repo and remove the need to invoke `typings` during install.
