### ISSUE TITLE
typescript 1.7.5 Error with all.d.ts Exported external package typings file cannot contain tripleslash references

### ISSUE THREAD

**Issue by vladimir-ivanov** [justindujardin/ng2-material#75]
ERROR in C:\sandbox\fipl-search\node_modules\ng2-material\all.d.ts
(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

ERROR in C:\sandbox\fipl-search\node_modules\ng2-material\all.d.ts
(1,1): error TS6053: File 'C:/sandbox/fipl-search/node_modules/node_modules/angular2/typings/browser.d.ts' not found.

**Comment by justindujardin** [comment]
@vladimir-ivanov This issue should be fixed in v0.2.5 which is now on NPM.  Please confirm and close.

**Comment by vladimir-ivanov** [comment]
thank you, works fine now :+1:
