### ISSUE TITLE
Icons on tabs

### ISSUE THREAD

**Issue by shawnrmoss** [justindujardin/ng2-material#79]
Is there a way to set icons on the tab buttons instead of setting the label values?

**Comment by forfuns** [comment]
`
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
`

it that your want ?

**Comment by justindujardin** [comment]
We removed the related component in favor of using: 
 - https://github.com/angular/material2/tree/master/src/lib/tabs
 - https://github.com/angular/material2/tree/master/src/lib/icon
