### ISSUE TITLE
Slidenav doesn't work (Plunker)

### ISSUE THREAD

**Issue by diamo1213** [justindujardin/ng2-material#85]
Hi,
here is a plunk [http://plnkr.co/edit/2cYsCt8y571j9eLeYsnO?p=preview](http://plnkr.co/edit/2cYsCt8y571j9eLeYsnO?p=preview)

and input doesn't work too

**Comment by diamo1213** [comment]
when i deal with local server 

`import {Component, OnInit} from 'angular2/core';
import {BackEnd} from './backend.service';
import {LoginCopm} from './login.comp';
import {MATERIAL_DIRECTIVES} from "ng2-material/all";

@Component({
    selector: 'my-app',
    templateUrl: './tmpl/app.html',
    styleUrls: ["./src/css/app.css"],
    directives: [LoginCopm, MATERIAL_DIRECTIVES],
    //providers: [BackEnd]
})

export class AppComponent {
    constructor(private _be:BackEnd) {}
}
`

i get:
SyntaxError: expected expression, got '<'
	Evaluating http://localhost:3002/ng2-material/all
	Error loading http://localhost:3002/app/boot.js
Stack trace:
bootstrap/</</__exec@http://localhost:3002/node_modules/systemjs/dist/system.src.js:1395:1
bootstrap/</</</entry.execute@http://localhost:3002/node_modules/systemjs/dist/system.src.js:3521:9
linkDynamicModule@http://localhost:3002/node_modules/systemjs..........

**Comment by justindujardin** [comment]
http://plnkr.co/edit/LEaCCHbIhrytDgCjuxJz?p=preview

You had a few things wrong, namely that the plunkr on the examples site is out of date.  I updated your plunkr to work.
