### ISSUE TITLE
Update angular2-seed fork for latest ng2-material builds

### ISSUE THREAD

**Issue by justindujardin** [justindujardin/ng2-material#86]
The angular2-seed project is out of date.

- [ ] update project to work with latest ng2-material npm version
- [ ] update demo to include a basic sidenav app template
- [ ] make any needed changes to `examples/routes/index.html` for the Starting from Scratch section

**Comment by JanStureNielsen** [comment]
Cool - thanks, Justin. I ended up using your site code, instead, which is a better fit for me, anyway.

**Comment by justindujardin** [comment]
Glad to hear it!

**Comment by d3viant0ne** [comment]
@justindujardin - I collaborate on the seed project, I'll pick this one up.

That said, I would prefer to wait until mgechev/angular2-seed#528 lands

**Comment by justindujardin** [comment]
@d3viant0ne that would be great, thanks!

**Comment by d3viant0ne** [comment]
@justindujardin - The odds of me getting to this tomorrow are slim. Realistically, it will be mid-week to get a PR open.

**Comment by justindujardin** [comment]
No problem, I have removed the reference to my fork of angular2-seed on the site for now. Just open one whenever you have time.

**Comment by d3viant0ne** [comment]
@justindujardin - I'll got most of this done. Need to tweak a few things visually & double check the prod build.

Should be finished by this afternoon.

**Comment by justindujardin** [comment]
Going to close this for now.
