### ISSUE TITLE
Strange bug in "input" example

### ISSUE THREAD

**Issue by metal3d** [justindujardin/ng2-material#89]
I was testing your nice work (really congrats !) and I found a strange behaviour on input example page.
https://justindujardin.github.io/ng2-material/#/components/input

On the last form, I quickly insert lot of chars (eg "fjeiofjziefjiozjfiozjfizjefozjfiz") and suddenly the form becomes crazy. It seems that form and model changes value several times per second as if one would change other, and vice-versa.

I'm using Chrome 50 on Fedora Linux 23 (x64)

One more time, very nice work !

**Comment by sylvaindumont** [comment]
Seems related to #55.
The input doesn't blink but have the same strange behavior when typing.

**Comment by metal3d** [comment]
yes it seems to be the same problem. I havn't seen this bug, maybe we can close this one and let #55 as the main issue ?

**Comment by justindujardin** [comment]
Closing as dup of #55
