### ISSUE TITLE
sidenav toggle() method should have a default parameter value

### ISSUE THREAD

**Issue by osechet** [justindujardin/ng2-material#90]
The sidenav's toggle method should define a default value for the visible parameter as it is done in backdrop : `toggle(visible: boolean = !this.visible)`.

**Comment by justindujardin** [comment]
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.
