### ISSUE TITLE
ngModel not working on radio

### ISSUE THREAD

**Issue by ZeBigDuck** [justindujardin/ng2-material#91]
Hi,

I'm experiencing issue with radio element.

In your examples, you're using [(value)] on the radio container. This is working, but if I want to use it in a form (as this should be the expected behaviour I guess), with ngControl and ngModel, this breaks angular.

How may I use radio with ngModel and ngControl ? Do you have an example ?

Thank you

**Comment by justindujardin** [comment]
The radio component has been replaced with the [Material2 radio](https://github.com/angular/material2/tree/master/src/components/radio) component as of version `0.4.1`.  Closing this issue.
