### ISSUE TITLE
Toggle Right Panel and Dialog Popup removing vertical scroll

### ISSUE THREAD

**Issue by kuncevic** [justindujardin/ng2-material#95]
After clicking on `Toggle Right` button Right Panel appeared but for some reason vertical scroll dissipated

<img width="330" alt="2016-03-04_13-39-06" src="https://cloud.githubusercontent.com/assets/1283734/13516510/06185d9c-e20f-11e5-93e6-dd3abd61cf59.png"><img width="330" alt="opera_2016-03-04_13-38-54" src="https://cloud.githubusercontent.com/assets/1283734/13516508/051ca56a-e20f-11e5-8170-9fbb2a9d70d4.png">

**Comment by mwiesmueller** [comment]
Is this about the same as in #156 ?

**Comment by kuncevic** [comment]
Yes sound like `overflow: hidden` getting set on body tag `<body cz-shortcut-listen="true" style="overflow: hidden;">` is a case.

There is two parts where that behavior talking place
https://justindujardin.github.io/ng2-material/#/components/sidenav 
https://justindujardin.github.io/ng2-material/#/components/dialog 

How did you find out that

**Comment by justindujardin** [comment]
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.
