### ISSUE TITLE
Link to Codepen from component examples

### ISSUE THREAD

**Issue by justindujardin** [justindujardin/ng2-material#98]
**Problem**
Component examples in the demo site require manual processing to get started with.  You have to come prepared with your own build process and extract the code, or use our grunt build process. This makes it difficult to start playing with ng2-material components.

**Solution**
Add "Edit in Codepen" button that launches a new pen with the current version of ng2-material linked in and the component example source/styles/markup inline.

- [ ] Add codepen icon button next to view source on component examples
- [ ] Use codepen API to post the component example contents to a new codepen
- [ ] Update codepen to properly reference CDN build for the current version in gh-pages

**Comment by justindujardin** [comment]
I looked into this and the experience is not very great. The trouble is that in order to really be able to edit the examples in a practical way, you need to be able to compile from Typescript and resolve the imports properly to angular2 and other es6 modules. The codepen API does not support this workflow.

Closing this for now, may revisit it later.

**Comment by Gregcop1** [comment]
Too bad, it was a great idea
